log_level: info

pod_namespace: nightly

prowjob_namespace: prow

# Report job status for presubmit and postsubmit
github_reporter:
  job_types_to_report:
    - presubmit
    - postsubmit

presubmits:
  giantswarm/releases:
  - name: dummy
    always_run: false
    spec:
      containers:
        - image: hello-world:latest
  - name: cis
    agent: tekton-pipeline
    max_concurrency: 3
    always_run: false
    skip_report: false
    pipeline_run_spec:
      pipelineRef:
        name: cis
      resources:
      - name: releases
        resourceRef:
          name: PROW_IMPLICIT_GIT_REF
    trigger: "/test cis"
    rerun_command: "/test cis"
  - name: cncf
    agent: tekton-pipeline
    max_concurrency: 3
    always_run: false
    skip_report: false
    pipeline_run_spec:
      pipelineRef:
        name: cncf
      timeout: 5h0m0s
      resources:
      - name: releases
        resourceRef:
          name: PROW_IMPLICIT_GIT_REF
    trigger: "/test cncf"
    rerun_command: "/test cncf"
