log_level: info

pod_namespace: nightly

prowjob_namespace: prow

# Report job status for presubmit and postsubmit
github_reporter:
  job_types_to_report:
    - presubmit
    - postsubmit

## Jobs can be defined in here or also pushed in a separate configmap
##
periodics:
  - name: hello-world-job
    interval: 15m
    spec:
      containers:
        - image: hello-world:latest

presubmits:
  giantswarm/releases:
  - name: dummy
    always_run: false
    spec:
      containers:
        - image: hello-world:latest
