log_level: info

pod_namespace: nightly

prowjob_namespace: prow

# Report job status for presubmit and postsubmit
github_reporter:
  job_types_to_report:
    - presubmit
    - postsubmit

periodics:
  - name: hello-world-job
    interval: 15m
    spec:
      containers:
        - image: hello-world:latest
