plugins:
  giantswarm/test-infra:
  - config-updater
  giantswarm:
  - dog
  - trigger

config_updater:
  maps:
    prow/config/configs.yaml:
      name: configs
    prow/config/plugins.yaml:
      name: plugins
