apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: app-test-preparation
  namespace: test-workloads
spec:
  workspaces:
  - name: cluster
    description: Cluster information is stored here.
  steps:
  - name: prepare-cluster
    image: quay.io/giantswarm/apptestctl:0.3.1-de5ceccf8a8e08b75af0d6d0a65600d1b21e9036
    script: |
      #!/bin/sh
      apptestctl bootstrap --kubeconfig "$(cat $(workspaces.cluster.path)/kubeconfig)"
