apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: apps
  namespace: test-workloads
spec:
  workspaces:
    - name: cluster
      description: Cluster information is stored here.
  steps:
    - name: download-sonobuoy-plugin
      image: busybox
      script: |
        #! /bin/sh
        wget -O $(workspaces.cluster.path)/giantswarm-plugin.yaml https://raw.githubusercontent.com/giantswarm/sonobuoy-plugin/master/giantswarm-plugin.yaml
    - name: run-tests
      image: quay.io/giantswarm/sonobuoy:v0.52.0-alpine-giantswarm
      env:
        - name: "CLUSTER_ID_PATH"
          value: $(workspaces.cluster.path)/cluster-id
      script: |
        #! /bin/sh
        /sonobuoy run \
            --kubeconfig "/etc/kubeconfig/$(cat $(workspaces.cluster.path)/provider)" \
            --namespace "$(cat "${CLUSTER_ID_PATH}")-sonobuoy" \
            --plugin $(workspaces.cluster.path)/giantswarm-plugin.yaml \
            --plugin-env giantswarm.CP_KUBECONFIG="$(cat /etc/kubeconfig/$(cat $(workspaces.cluster.path)/provider))" \
            --plugin-env giantswarm.CLUSTER_ID="$(cat "${CLUSTER_ID_PATH}")" \
            --plugin-env giantswarm.E2E_FOCUS="App" \
            --mode=quick \
            --wait
      volumeMounts:
        - mountPath: /etc/kubeconfig
          name: kubeconfig
  volumes:
    - name: kubeconfig
      secret:
        secretName: sonobuoy-kubeconfig
