apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: aws-cnfm
  namespace: test-workloads
spec:
  volumes:
    - name: kubeconfig
      secret:
        secretName: standup-kubeconfig
  workspaces:
    - name: cluster
      description: Run the aws conformance test plan.
  params:
    - name: cnfm-plan
      type: string
      description: CNFM plan to execute
  steps:
    - name: run-tests
      image: quay.io/giantswarm/awscnfm:15.2.1
      env:
        - name: CNFM_PLAN
          value: $(params.cnfm-plan)
      volumeMounts:
        - name: kubeconfig
          mountPath: /etc/controlplane
      script: |
        #! /bin/sh
        
        export AWSCNFM_CONTROLPLANE_KUBECONFIG=/etc/controlplane/aws
        export AWSCNFM_CREATE_RELEASEVERSION=$(cat $(workspaces.cluster.path)/release-id)

        awscnfm plan $CNFM_PLAN --output $(workspaces.cluster.path)
