apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: aws-cnfm-update
  namespace: test-workloads
spec:
  volumes:
    - name: kubeconfig
      secret:
        secretName: standup-kubeconfig
  params:
    - name: release-id
      type: string
      description: Release to test
    - name: cnfm-plan
      type: string
      description: CNFM plan to execute
  results:
  - name: cluster-id
    description: The ID of the created cluster.
  steps:
    - name: run-tests
      image: quay.io/giantswarm/awscnfm:15.2.1
      env:
        - name: RELEASE_ID
          value: $(params.release-id)
        - name: CNFM_PLAN
          value: $(params.cnfm-plan)
      volumeMounts:
        - name: kubeconfig
          mountPath: /etc/controlplane
      script: |
        #! /bin/sh
        
        export AWSCNFM_CONTROLPLANE_KUBECONFIG=/etc/controlplane/aws
        export AWSCNFM_CREATE_RELEASEVERSION=v14.2.2 
        export AWSCNFM_UPDATE_RELEASEVERSION=$RELEASE_ID

        awscnfm plan $CNFM_PLAN --output /tmp/cluster-id
        cat /tmp/cluster-id > $(results.cluster-id.path)