apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: aws
  namespace: test-workloads
spec:
  workspaces:
  - name: cluster
    description: Run the aws conformance test plan of the most basic cluster scope in order to cover cluster creation and deletion.
  steps:
  - name: run-tests
    image: quay.io/giantswarm/awscnfm:12.1.4-5798a32e3223ab4b8852d8d02583f92d9d0bee74
    env:
      - name: "AWSCNFM_TENANTCLUSTER_KUBECONFIG"
        value: $(workspaces.cluster.path)/kubeconfig
    script: |
      #! /bin/sh
      awscnfm cl001 ac000 execute
