apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: azure
  namespace: test-workloads
spec:
  workspaces:
    - name: cluster
      description: Cluster information is stored here.
  params:
  - name: test-deletion
    description: Whether or not test deletion of clusters.
    default: "1"
  steps:
    - name: run-tests
      image: quay.io/giantswarm/run-sonobuoy-tests
      env:
        - name: TC_KUBECONFIG_PATH
          value: $(workspaces.cluster.path)/kubeconfig
        - name: KUBECONFIG_PATH
          value: /etc/kubeconfig/azure
        - name: CLUSTER_ID_PATH
          value: $(workspaces.cluster.path)/cluster-id
        - name: RESULTS_PATH
          value: $(workspaces.cluster.path)/sonobuoy-results.tar
        - name: PROVIDER
          value: azure
        - name: TEST_DELETION
          value: $(params.test-deletion)
      script: |
        #! /bin/sh
        run-sonobuoy-tests giantswarm
      volumeMounts:
        - mountPath: /etc/kubeconfig
          name: kubeconfig
  volumes:
    - name: kubeconfig
      secret:
        secretName: sonobuoy-kubeconfig
