apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: azure
  namespace: test-workloads
spec:
  workspaces:
    - name: cluster
      description: Cluster information is stored here.
  steps:
    - env:
        - name: KUBECONFIG
          value: $(workspaces.cluster.path)/kubeconfig
        - name: CP_KUBECONFIG
          value: /etc/kubeconfig
        - name: CLUSTER_ID
          value: $(cat $(workspaces.cluster.path)/cluster-id)
        - name: RESULTS_PATH
          value: $(workspaces.cluster.path)/sonobuoy-results.tar
      image: quay.io/giantswarm/conformance-tests
      name: run-tests
      resources: {}
      script: |
        #! /bin/sh
        sonobuoy run \
          --kubeconfig "${KUBECONFIG}" \
          --plugin https://raw.githubusercontent.com/giantswarm/sonobuoy-plugin/master/giantswarm-plugin.yaml \
          --plugin-env giantswarm.KUBECONFIG="${KUBECONFIG}" \
          --plugin-env giantswarm.CP_KUBECONFIG="${CP_KUBECONFIG}" \
          --plugin-env giantswarm.CLUSTER_ID="${CLUSTER_ID}" \
          --mode=certified-conformance \
          --wait
      volumeMounts:
        - mountPath: /etc/kubeconfig
          name: kubeconfig
  volumes:
    - name: kubeconfig
      secret:
        secretName: standup-kubeconfig
