apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: azure
  namespace: test-workloads
spec:
  workspaces:
    - name: cluster
      description: Cluster information is stored here.
  params:
  - name: test-deletion
    description: Whether or not test deletion of clusters.
    default: "1"
    type: string
  steps:
    - name: run-tests
      image: quay.io/giantswarm/run-sonobuoy-tests
      env:
        - name: TC_KUBECONFIG_PATH
          value: $(workspaces.cluster.path)/kubeconfig
        - name: KUBECONFIG_PATH
          value: /etc/kubeconfig/azure
        - name: CLUSTER_ID_PATH
          value: $(workspaces.cluster.path)/cluster-id
        - name: PROVIDER
          value: azure
        - name: TEST_DELETION
          value: $(params.test-deletion)
      script: |
        #! /bin/sh
        sonobuoy run \
            --kubeconfig "${KUBECONFIG_PATH}" \
            --namespace "$(cat "${CLUSTER_ID_PATH}")-sonobuoy" \
            --plugin https://raw.githubusercontent.com/giantswarm/sonobuoy-plugin/master/giantswarm-plugin.yaml \
            --plugin-env giantswarm.TC_KUBECONFIG="$(cat "${TC_KUBECONFIG_PATH}")" \
            --plugin-env giantswarm.CP_KUBECONFIG="$(cat "${KUBECONFIG_PATH}")" \
            --plugin-env giantswarm.CLUSTER_ID="$(cat "${CLUSTER_ID_PATH}")" \
            --plugin-env giantswarm.PROVIDER="${PROVIDER}" \
            --plugin-env giantswarm.TEST_DELETION="${TEST_DELETION}" \
            --mode=certified-conformance \
            --wait
      volumeMounts:
        - mountPath: /etc/kubeconfig
          name: kubeconfig
  volumes:
    - name: kubeconfig
      secret:
        secretName: sonobuoy-kubeconfig
