apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: calculate-versions
  namespace: test-workloads
spec:
  params:
  - name: source-repo-name
    type: string
  - name: provider
    type: string
  - name: installation
    type: string
  - name: cluster-chart
    type: string
  - name: default-apps-chart
    type: string
  volumes:
  - name: kubeconfig
    secret:
      secretName: standup-kubeconfig
  workspaces:
  - name: cluster
    description: Cluster information is stored here.
  resources:
    inputs:
    - name: source-repo
      type: git
  results:
  - name: cluster-id
    description: The ID of the created cluster.
  - name: organization
    description: Organization that owns the cluster.
  - name: cluster-app-chart-version
    description: Version to use when installing the cluster app.
  - name: cluster-app-catalog
    description: Catalog to use when installing the cluster app.
  - name: default-apps-chart-version
    description: Version to use when installing default apps.
  - name: default-apps-catalog
    description: Catalog to use when installing the default apps app.
  steps:
  - name: chown-source-repo
    command:
    - chown
    - -R
    - 1000:1000
    - /workspace/source-repo
    image: quay.io/giantswarm/standup:3.4.0
    securityContext:
      runAsUser: 0
      runAsGroup: 0
  - name: calculate-inputs
    image: quay.io/giantswarm/standup:3.4.0
    env:
    - name: SOURCE_REPO_NAME
      value: $(params.source-repo-name)
    - name: INSTALLATION
      value: $(params.installation)
    - name: CLUSTER_CHART
      value: $(params.cluster-chart)
    - name: DEFAULT_APPS_CHART
      value: $(params.default-apps-chart)
    script: |
      #! /bin/sh

      set -e
      set -x

      cd /workspace/source-repo
      git fetch --unshallow
      parent_tag=$(git describe --tags --abbrev=0 | sed -e "s/^v//")
      hash=$(git describe --always --abbrev=0)
      repo_version=${parent_tag}-${hash}

      if [ "$SOURCE_REPO_NAME" = "$DEFAULT_APPS_CHART" ]; then
        app_flags="--default-apps-catalog cluster-test --default-apps-version $repo_version"
        echo -n "" > $(results.cluster-app-chart-version.path)
        echo -n "cluster" > $(results.cluster-app-catalog.path)
        echo -n "${repo_version}" > $(results.default-apps-chart-version.path)
        echo -n "cluster-test" > $(results.default-apps-catalog.path)
      else
        app_flags="--cluster-catalog cluster-test --cluster-version $repo_version"
        echo -n "${repo_version}" > $(results.cluster-app-chart-version.path)
        echo -n "cluster-test" > $(results.cluster-app-catalog.path)
        echo -n "" > $(results.default-apps-chart-version.path)
        echo -n "cluster" > $(results.default-apps-catalog.path)
      fi

      echo $app_flags > $(workspaces.cluster.path)/kubectl-gs-flags
