apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cis
  namespace: test-workloads
spec:
  workspaces:
  - name: cluster
    description: Cluster information is stored here.
  steps:
  - name: run-tests
    image: quay.io/giantswarm/run-sonobuoy-tests
    env:
      - name: "KUBECONFIG_PATH"
        value: $(workspaces.cluster.path)/kubeconfig
      - name: "RESULTS_PATH"
        value: $(workspaces.cluster.path)/sonobuoy-results.tar
    script: |
      #! /bin/sh
      run-sonobuoy-tests cis
