apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: cis
  namespace: nightly
spec:
  workspaces:
    - name: cluster
      description: a folder containing a cluster kubeconfig
  steps:
    - name: run-tests
      image: quay.io/giantswarm/conformance-tests
      script: |
        #! /bin/bash
        run-sonobuoy-tests cis

