apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cis
  namespace: test-workloads
spec:
  workspaces:
  - name: cluster
    description: Cluster information is stored here.
  steps:
  - name: run-tests
    image: quay.io/giantswarm/sonobuoy-alpine:0.0.0-234dc078a0eb416cf9343ff8097f23a8bd67debf
    env:
      - name: "KUBECONFIG_PATH"
        value: $(workspaces.cluster.path)/kubeconfig
    script: |
      #! /bin/sh
      /sonobuoy run \
        --kubeconfig "${KUBECONFIG_PATH}" \
        --plugin https://raw.githubusercontent.com/vmware-tanzu/sonobuoy-plugins/master/cis-benchmarks/kube-bench-plugin.yaml \
        --plugin https://raw.githubusercontent.com/vmware-tanzu/sonobuoy-plugins/master/cis-benchmarks/kube-bench-master-plugin.yaml \
        --plugin-env kube-bench-master.KUBERNETES_VERSION=1.19 --plugin-env kube-bench-node.KUBERNETES_VERSION=1.19 \
        --wait
