apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cis
  namespace: test-workloads
spec:
  workspaces:
  - name: cluster
    description: Cluster information is stored here.
  steps:
  - name: run-tests
    image: quay.io/giantswarm/sonobuoy:v0.56.17-alpine-giantswarm
    env:
      - name: WC_KUBECONFIG
        value: "$(workspaces.cluster.path)/kubeconfig"
    script: |
      #! /bin/sh

      /sonobuoy run \
        --kubeconfig "${WC_KUBECONFIG}" \
        --plugin https://raw.githubusercontent.com/vmware-tanzu/sonobuoy-plugins/master/cis-benchmarks/kube-bench-plugin.yaml \
        --plugin https://raw.githubusercontent.com/vmware-tanzu/sonobuoy-plugins/master/cis-benchmarks/kube-bench-master-plugin.yaml \
        --plugin-env kube-bench-master.KUBERNETES_VERSION=1.19 --plugin-env kube-bench-node.KUBERNETES_VERSION=1.19 \
        --wait
