apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
  namespace: test
spec:
  params:
  - name: gs-token-secret
    default: gs-token-secret
  workspaces:
  - name: cluster
    description: Cluster information is stored here.
  steps:
  - name: cleanup
    image: quay.io/giantswarm/standup
    env:
    - name: TOKEN
      valueFrom:
        secretKeyRef:
          name: $(params.gs-token-secret)
          key: token
    script: |
      #! /bin/sh
      standup cleanup \
      --in-cluster \
      --endpoint http://api-service.giantswarm.svc.cluster.local:8000 \
      --token ${TOKEN} \
      --cluster $(cat $(workspaces.cluster.path)/cluster-id)
