apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
  namespace: test-workloads
spec:
  params:
  workspaces:
  - name: cluster
    description: Cluster information is stored here.
  steps:
  - name: cleanup
    image: quay.io/giantswarm/standup
    script: |
      #! /bin/sh
      standup cleanup \
      --config /etc/endpoints-config/config \
      --kubeconfig /etc/kubeconfig/kubeconfig \
      --cluster $(cat $(workspaces.cluster.path)/cluster-id)
      --provider $(cat $(workspaces.cluster.path)/provider)
