apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
  namespace: test-workloads
  labels:
    app.kubernetes.io/name: "standup"
spec:
  volumes:
    - name: endpoints-config
      secret:
        secretName: standup-endpoints-config
    - name: kubeconfig
      secret:
        secretName: standup-kubeconfig
  params:
    - name: release-id
      type: string
      description: Release to test
    - name: installation
      type: string
      description: Installation to test
    - name: cluster-id
      type: string
      description: Cluster ID
  steps:
  - name: cleanup
    image: quay.io/giantswarm/standup:3.0.0
    env:
      - name: RELEASE_ID
        value: $(params.release-id)
      - name: CLUSTER_ID
        value: $(params.cluster-id)
      - name: INSTALLATION
        value: $(params.installation)
    volumeMounts:
      - name: endpoints-config
        mountPath: /etc/endpoints-config
      - name: kubeconfig
        mountPath: /etc/kubeconfig
    script: |
      #! /bin/sh
      standup cleanup \
      --config /etc/endpoints-config/config \
      --kubeconfig /etc/kubeconfig \
      --cluster $CLUSTER_ID \
      --installation $INSTALLATION_ID \
      --release $RELEASE_ID
