apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
  namespace: test-workloads
  labels:
    app.kubernetes.io/name: "standup"
spec:
  volumes:
    - name: endpoints-config
      secret:
        secretName: standup-endpoints-config
    - name: kubeconfig
      secret:
        secretName: standup-kubeconfig
  workspaces:
  - name: cluster
    description: Cluster information is stored here.
  steps:
  - name: cleanup
    image: quay.io/giantswarm/standup:3.2.0
    volumeMounts:
      - name: endpoints-config
        mountPath: /etc/endpoints-config
      - name: kubeconfig
        mountPath: /etc/kubeconfig
    script: |
      #! /bin/sh

      export KUBECONFIG=/etc/kubeconfig/$(cat $(workspaces.cluster.path)/installation)

      kubectl -n org-giantswarm delete cluster.cluster.x-k8s.io $(cat $(workspaces.cluster.path)/cluster-id) || true
      kubectl delete release $(cat $(workspaces.cluster.path)/release-id) || true
