apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup-capi-hybrid
  namespace: test-workloads
spec:
  volumes:
    - name: kubeconfig
      secret:
        secretName: standup-kubeconfig
  workspaces:
  - name: cluster
    description: Cluster information is stored here.
  params:
  - name: MC_KUBECONFIG
    type: string
    description: "Path of kubeconfig file to access test management cluster"
  - name: RELEASE
    type: string
    description: Release ID to use when creating the cluster.
  steps:
  - name: cleanup
    image: quay.io/giantswarm/standup:3.4.2
    env:
      - name: KUBECONFIG
        value: $(params.MC_KUBECONFIG)
      - name: RELEASE
        value: $(params.RELEASE)
    volumeMounts:
      - name: kubeconfig
        mountPath: /etc/kubeconfig
    script: |
      #! /bin/sh

      echo "Provider: '${PROVIDER}'"
      echo "Region: '${REGION}'"
      echo "MC Kubeconfig path: '${KUBECONFIG}'"
      echo "Release: '${RELEASE}'"

      kubectl -n org-giantswarm delete cluster.cluster.x-k8s.io $(cat $(workspaces.cluster.path)/cluster-id) || true
      kubectl delete release $RELEASE || true
