apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup-capi-pure
  namespace: test-workloads
spec:
  volumes:
    - name: kubeconfig
      secret:
        secretName: standup-kubeconfig
  workspaces:
  - name: cluster
    description: Cluster information is stored here.
  params:
  - name: cluster-id
    type: string
    description: Name of the cluster
  - name: organization
    type: string
    description: Organization that owns the cluster
  steps:
  - name: cleanup
    image: quay.io/giantswarm/kubectl-gs:2.37.0
    volumeMounts:
      - name: kubeconfig
        mountPath: /etc/kubeconfig
    script: |
      #! /bin/sh

      set -e

      export KUBECONFIG=/etc/kubeconfig/$(cat $(workspaces.cluster.path)/installation)

      kubectl -n org-$(params.organization) delete app $(params.cluster-id) $(params.cluster-id)-default-apps --ignore-not-found
