apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
  namespace: test-workloads
  labels:
    app.kubernetes.io/name: "standup"
spec:
  volumes:
    - name: endpoints-config
      secret:
        secretName: standup-endpoints-config
    - name: kubeconfig
      secret:
        secretName: standup-kubeconfig
  workspaces:
  - name: cluster
    description: Cluster information is stored here.
  steps:
  - name: cleanup
    image: quay.io/giantswarm/standup:1.1.1-63036dfea4a1a63f34c3fc3a663256e849842859
    volumeMounts:
      - name: endpoints-config
        mountPath: /etc/endpoints-config
      - name: kubeconfig
        mountPath: /etc/kubeconfig
    script: |
      #! /bin/sh
      standup cleanup \
      --config /etc/endpoints-config/config \
      --kubeconfig /etc/kubeconfig \
      --cluster $(cat $(workspaces.cluster.path)/cluster-id) \
      --provider $(cat $(workspaces.cluster.path)/provider) \
      --release $(cat $(workspaces.cluster.path)/release-id)
