apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
  namespace: test-workloads
spec:
  volumes:
    - name: endpoints-config
      secret:
        secretName: standup-endpoints-config
    - name: kubeconfig
      secret:
        secretName: standup-kubeconfig
  workspaces:
  - name: cluster
    description: Cluster information is stored here.
  steps:
  - name: cleanup
    image: quay.io/giantswarm/standup
    volumeMounts:
      - name: endpoints-config
        mountPath: /etc/endpoints-config
      - name: kubeconfig
        mountPath: /etc/kubeconfig
    script: |
      #! /bin/sh
      standup cleanup \
      --config /etc/endpoints-config/config \
      --kubeconfig /etc/kubeconfig/kubeconfig \
      --cluster $(cat $(workspaces.cluster.path)/cluster-id) \
      --provider $(cat $(workspaces.cluster.path)/provider)
