apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cncf
  namespace: test-workloads
spec:
  workspaces:
  - name: cluster
    description: Cluster information is stored here.
  params:
  - name: PROVIDER
    type: string
    default: ""
    description: Name of the provider (either 'aws' or 'azure')
  - name: REGION
    type: string
    default: "default"
    description: Name of the AWS provider (can be 'default', meaning frankfurt, or 'china')
  - name: MC_KUBECONFIG
    type: string
    description: "Path of kubeconfig file to access test management cluster"
  steps:
  - name: run-tests
    image: quay.io/giantswarm/sonobuoy:v0.56.17-alpine-giantswarm
    securityContext:
      runAsUser: 0
      runAsGroup: 0
    env:
      - name: PROVIDER
        value: $(params.PROVIDER)
      - name: REGION
        value: $(params.REGION)
      - name: MC_KUBECONFIG
        value: $(params.MC_KUBECONFIG)
      - name: "WC_KUBECONFIG"
        value: $(workspaces.cluster.path)/kubeconfig
    script: |
      #! /bin/sh
      echo "Provider: '${PROVIDER}'"
      echo "Region: '${REGION}'"
      echo "MC Kubeconfig path: '${MC_KUBECONFIG}'"
      echo "WC Kubeconfig path: '${WC_KUBECONFIG}'"

      PSS=$(cat <<-END
      apiVersion: kyverno.io/v2alpha1
      kind: PolicyException
      metadata:
        name: sonobuoy-policy-exceptions
        namespace: giantswarm
      spec:
        background: true
        exceptions:
        - policyName: disallow-host-path
          ruleNames:
          - host-path
          - autogen-host-path
          - autogen-cronjob-host-path
        - policyName: require-run-as-nonroot
          ruleNames:
          - run-as-non-root
          - autogen-run-as-non-root
          - autogen-cronjob-run-as-non-root
        - policyName: require-run-as-non-root-user
          ruleNames:
          - run-as-non-root-user
          - autogen-run-as-non-root-user
        - policyName: restrict-volume-types
          ruleNames:
          - restricted-volumes
          - autogen-restricted-volumes
          - autogen-cronjob-restricted-volumes
        - policyName: disallow-capabilities-strict
          ruleNames:
          - require-drop-all
          - adding-capabilities-strict
          - autogen-require-drop-all
          - autogen-cronjob-require-drop-all
          - autogen-adding-capabilities-strict
          - autogen-cronjob-adding-capabilities-strict
        - policyName: disallow-privilege-escalation
          ruleNames:
          - privilege-escalation
          - autogen-privilege-escalation
        - policyName: restrict-seccomp-strict
          ruleNames:
          - check-seccomp-strict
          - autogen-check-seccomp-strict
        match:
          any:
          - resources:
              kinds:
              - Deployment
              - ReplicaSet
              - Pod
              - StatefulSet
              namespaces:
              - sonobuoy
              names:
              - '*'
      END
      )

      echo "$PSS" | kubectl --kubeconfig "${WC_KUBECONFIG}" apply -f -

      /sonobuoy run --kubeconfig "${WC_KUBECONFIG}" --mode=certified-conformance --wait
