apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cncf
  namespace: test-workloads
spec:
  params:
  - name: kubeconfig
    type: string
    description: Kubeconfig of the created cluster.
  steps:
  - name: run-tests
    image: quay.io/giantswarm/sonobuoy:v0.53.2-alpine-giantswarm
    env:
      - name: "KUBECONFIG_PATH"
        value: $(workspaces.cluster.path)/kubeconfig
    script: |
      #! /bin/sh
      echo $(params.kubeconfig) > /tmp/kubeconfig
      /sonobuoy run --kubeconfig /tmp/kubeconfig --mode=certified-conformance --wait
