apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: cncf
  namespace: nightly
spec:
  volumes:
  - name: cluster
    secret:
      secretName: cluster
  workspaces:
  - name: cluster
    description: The folder where to get the kubeconfig from
  steps:
  - name: run-tests
    image: quay.io/giantswarm/conformance-tests
    volumeMounts:
    - mountPath: /cluster
      name: cluster
    env:
      - name: "KUBECONFIG_PATH"
        value: $(workspaces.cluster.path)/kubeconfig
    script: |
      #! /bin/sh
      run-sonobuoy-tests cncf
