apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: cncf
  namespace: nightly
spec:
  volumes:
  - name: cluster
    secret:
      secretName: cluster
  steps:
  - name: run-tests
    image: quay.io/giantswarm/conformance-tests
    volumeMounts:
    - mountPath: /cluster
      name: cluster
    env:
      - name: "KUBECONFIG_PATH"
        value: "/cluster/kubeconfig"
    script: |
      #! /bin/sh
      run-sonobuoy-tests cncf
