apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cncf
  namespace: test-workloads
spec:
  workspaces:
  - name: cluster
    description: Cluster information is stored here.
  steps:
  - name: run-tests
    image: quay.io/giantswarm/sonobuoy-alpine:0.0.0-c9ca8ce9fecc3577efcad9f1d3edba3d984a4821
    env:
      - name: "KUBECONFIG_PATH"
        value: $(workspaces.cluster.path)/kubeconfig
    script: |
      #! /bin/sh
      /sonobuoy run --kubeconfig "${KUBECONFIG_PATH}" --mode=certified-conformance --wait
