apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: create-cluster
  namespace: test-workloads
spec:
  params:
  - name: create-extra-args
    type: array
    description: Extra args to pass to the create command
  resources:
    inputs:
    - name: releases
      type: git
  volumes:
  - name: endpoints-config
    secret:
      secretName: standup-endpoints-config
  - name: kubeconfig
    secret:
      secretName: standup-kubeconfig
  workspaces:
  - name: cluster
    description: Cluster information is stored here.
  steps:
  - name: chown-releases
    command:
    - chown
    - -R
    - 1000:1000
    - /workspace
    image: quay.io/giantswarm/standup
    securityContext:
      runAsUser: 0
      runAsGroup: 0
  - name: create-cluster
    image: quay.io/giantswarm/standup
    volumeMounts:
      - name: endpoints-config
        mountPath: /etc/endpoints-config
      - name: kubeconfig
        mountPath: /etc/kubeconfig
    script: |
      #! /bin/sh
      standup create \
      --config /etc/endpoints-config/config \
      --kubeconfig /etc/kubeconfig/kubeconfig \
      --releases /workspace/releases \
      --output $(workspaces.cluster.path) \
      $(params.create-extra-args[*])
