apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: create-cluster
  namespace: test-workloads
spec:
  resources:
    inputs:
    - name: releases
      type: git
  volumes:
  - name: endpoints-config
    secret:
      secretKeyRef: standup-endpoints-config
  - name: kubeconfig
    secret:
      secretKeyRef: standup-kubeconfig
  workspaces:
  - name: cluster
    description: Cluster information is stored here.
  steps:
  - name: chown-releases
    volumeMounts:
      - name: endpoints-config
      - name: kubeconfig
    command:
    - chown
    - -R
    - 1000:1000
    - /workspace
    image: quay.io/giantswarm/standup
    securityContext:
      runAsUser: 0
      runAsGroup: 0
  - name: create-cluster
    image: quay.io/giantswarm/standup:tc-to-cp
    script: |
      #! /bin/sh
      standup create \
      --config /etc/endpoints-config/standup-endpoints-config \
      --kubeconfig /etc/kubeconfig/standup-kubeconfig \
      --releases /workspace/releases \
      --output-kubeconfig $(workspaces.cluster.path)/kubeconfig \
      --output-cluster-id $(workspaces.cluster.path)/cluster-id
