apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: create-cluster
  namespace: test-workloads
  labels:
    app.kubernetes.io/name: "standup"
spec:
  volumes:
  - name: endpoints-config
    secret:
      secretName: standup-endpoints-config
  - name: kubeconfig
    secret:
      secretName: standup-kubeconfig
  params:
  - name: installation
    type: string
    description: Installation where the cluster will be created.
  - name: release-id
    type: string
    description: Release ID to use when creating the cluster.
  results:
  - name: cluster-id
    description: The ID of the created cluster.
  - name: kubeconfig
    description: Kubeconfig of the created cluster.
  - name: provider
    description: Provider of the created cluster.
  steps:
  - name: create-cluster
    image: quay.io/giantswarm/standup:3.0.0
    volumeMounts:
      - name: endpoints-config
        mountPath: /etc/endpoints-config
      - name: kubeconfig
        mountPath: /etc/kubeconfig
    script: |
      #! /bin/sh
      standup create cluster \
      --config /etc/endpoints-config/config \
      --kubeconfig /etc/kubeconfig \
      --release $(params.release-id) \
      --installation $(params.installation) \
      --output ~/

      cat ~/cluster-id > $(results.cluster-id.path)
      cat ~/kubeconfig > $(results.kubeconfig.path)
      cat ~/provider > $(results.provider.path)