apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: create-release
  namespace: test-workloads
spec:
  resources:
    inputs:
    - name: releases
      type: git
  volumes:
  - name: endpoints-config
    secret:
      secretName: standup-endpoints-config
  - name: kubeconfig
    secret:
      secretName: standup-kubeconfig
  workspaces:
  - name: cluster
    description: Cluster information is stored here.
  steps:
  - name: chown-releases
    command:
    - chown
    - -R
    - 1000:1000
    - /workspace
    image: quay.io/giantswarm/standup:1.0.0
    securityContext:
      runAsUser: 0
      runAsGroup: 0
  - name: create-release
    image: quay.io/giantswarm/standup:1.0.0-c6235d830b1a6f7b7540d9d60d0d1fe666b40709
    volumeMounts:
      - name: endpoints-config
        mountPath: /etc/endpoints-config
      - name: kubeconfig
        mountPath: /etc/kubeconfig
    script: |
      #! /bin/sh
      standup create release \
      --config /etc/endpoints-config/config \
      --kubeconfig /etc/kubeconfig/kubeconfig \
      --releases /workspace/releases \
      --output $(workspaces.cluster.path)
