apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: create-cluster
  namespace: test-workloads
spec:
  volumes:
  - name: endpoints-config
    secret:
      secretName: standup-endpoints-config
  - name: kubeconfig
    secret:
      secretName: standup-kubeconfig
  workspaces:
  - name: cluster
    description: Cluster information is stored here.
  steps:
  - name: create-cluster
    image: quay.io/giantswarm/standup:1.0.0-c6235d830b1a6f7b7540d9d60d0d1fe666b40709
    volumeMounts:
      - name: endpoints-config
        mountPath: /etc/endpoints-config
      - name: kubeconfig
        mountPath: /etc/kubeconfig
    script: |
      #! /bin/sh
      standup create cluster \
      --config /etc/endpoints-config/config \
      --kubeconfig /etc/kubeconfig/kubeconfig \
      --release $(cat $(workspaces.cluster.path)/release-id) \
      --output $(workspaces.cluster.path)
