apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: create-cluster
  namespace: nightly
spec:
  resources:
    inputs:
    - name: releases
      type: git
  workspaces:
  - name: cluster
    description: The folder where to put the kubeconfig of the newly created cluster
  params:
  - name: gs-token-secret
    default: gs-token-secret
  results:
  - name: cluster-id
    description: The cluster id of the newly created cluster
  steps:
  - name: chown-releases
    command:
    - chown
    - -R
    - 1000:1000
    - /workspace
    image: quay.io/giantswarm/standup
    securityContext:
      runAsUser: 0
      runAsGroup: 0
  - name: create-cluster
    image: quay.io/giantswarm/standup
    env:
    - name: TOKEN
      valueFrom:
        secretKeyRef:
          name: $(params.gs-token-secret)
          key: token
    args:
    - "create"
    - "--in-cluster"
    - "--token"
    - "$(TOKEN)"
    - "--provider"
    - "aws"
    - "--endpoint"
    - "http://api-service.giantswarm.svc.cluster.local:8000"
    - "--releases"
    - "/workspace/releases"
    - "--output-kubeconfig"
    - $(workspaces.cluster.path)/kubeconfig
    - "--output-cluster-id"
    - $(results.cluster-id.path)
