apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: create-release
  namespace: test-workloads
  labels:
    app.kubernetes.io/name: "standup"
spec:
  params:
    - name: pipeline-name
      type: string
      default: "generic"
      description: Name of the pipeline running this task.
  resources:
    inputs:
    - name: releases
      type: git
  volumes:
  - name: endpoints-config
    secret:
      secretName: standup-endpoints-config
  - name: kubeconfig
    secret:
      secretName: standup-kubeconfig
  results:
  - name: release-id
    description: The ID of the created release.
  - name: installation
    description: The ID of the installation.
  - name: provider
    description: Provider of the created cluster.
  steps:
  - name: chown-releases
    command:
    - chown
    - -R
    - 1000:1000
    - /workspace
    image: quay.io/giantswarm/standup:3.2.0
    securityContext:
      runAsUser: 0
      runAsGroup: 0
  - name: create-release
    image: quay.io/giantswarm/standup:3.2.0
    env:
      - name: PIPELINE_NAME
        value: $(params.pipeline-name)
    volumeMounts:
      - name: endpoints-config
        mountPath: /etc/endpoints-config
      - name: kubeconfig
        mountPath: /etc/kubeconfig
    script: |
      #! /bin/sh
      standup create release \
      --config /etc/endpoints-config/config \
      --kubeconfig /etc/kubeconfig \
      --releases /workspace/releases \
      --output /workspace \
      --pipeline "${PIPELINE_NAME}"

      cat /workspace/release-id > $(results.release-id.path)
      cat /workspace/installation > $(results.installation.path)
      cat /workspace/provider > $(results.provider.path)
