apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: create-cluster-stable
  namespace: test-workloads
  labels:
    app.kubernetes.io/name: "standup"
spec:
  volumes:
  - name: endpoints-config
    secret:
      secretName: standup-endpoints-config
  - name: kubeconfig
    secret:
      secretName: standup-kubeconfig
  workspaces:
  - name: cluster
    description: Cluster information is stored here.
  steps:
  - name: create-cluster-stable
    image: quay.io/giantswarm/standup:2.5.0
    volumeMounts:
      - name: endpoints-config
        mountPath: /etc/endpoints-config
      - name: kubeconfig
        mountPath: /etc/kubeconfig
    script: |
      #! /bin/sh
      LATEST_STABLE_RELEASE=$(kubectl --kubeconfig /etc/kubeconfig/azure get releases -o json | jq -r '[.items | sort_by(.metadata.name) | reverse[] | select(.metadata.name | test("v[0-9]*\\.[0-9]*\\.[0-9]*$")) ][].metadata.name' | head -n1)
      echo "Creating cluster using release ${LATEST_STABLE_RELEASE}"
      standup create cluster \
      --config /etc/endpoints-config/config \
      --kubeconfig /etc/kubeconfig \
      --release ${LATEST_STABLE_RELEASE} \
      --provider $(cat $(workspaces.cluster.path)/provider) \
      --output $(workspaces.cluster.path)

      cat $(workspaces.cluster.path)/cluster-id > $(results.cluster-id.path)
