apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: create-cluster
  namespace: nightly
spec:
  resources:
    inputs:
    - name: releases
      type: git
  workspaces:
  - name: cluster
    description: Cluster information is stored here.
  params:
  - name: gs-token-secret
    default: gs-token-secret
  steps:
  - name: chown-releases
    command:
    - chown
    - -R
    - 1000:1000
    - /workspace
    image: quay.io/giantswarm/standup
    securityContext:
      runAsUser: 0
      runAsGroup: 0
  - name: create-cluster
    image: quay.io/giantswarm/standup
    env:
    - name: TOKEN
      valueFrom:
        secretKeyRef:
          name: $(params.gs-token-secret)
          key: token
    script: |
      #! /bin/sh
      standup create \
      --in-cluster \
      --endpoint http://api-service.giantswarm.svc.cluster.local:8000 \
      --token ${TOKEN} \
      --releases /workspace/releases \
      --output-kubeconfig $(workspaces.cluster.path)/kubeconfig \
      --output-cluster-id $(workspaces.cluster.path)/cluster-id
