apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: create-cluster
  namespace: nightly
spec:
  resources:
    inputs:
    - name: releases
      type: git
    - name: gs-token-secret
      type: string
      default: gs-token-secret
  workspaces:
  - name: cluster
    description: The folder where to put the kubeconfig of the newly created cluster
  steps:
  - name: create-cluster
    # This needs to become the image that has gsctl and standup commands
    image: quay.io/giantswarm/standup
    env:
    - name: TOKEN
      valueFrom:
        secretKeyRef:
          name: $(params.gs-token-secret)
          key: token
    command: ["create"]
    args:
    - "--in-cluster"
    - "--token"
    - "$TOKEN"
    - "--provider"
    - "aws"
    - "--output"
    - $(workspaces.cluster.path)/kubeconfig
