apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: create-cluster-stable
  namespace: test-workloads
  labels:
    app.kubernetes.io/name: "standup"
spec:
  volumes:
  - name: endpoints-config
    secret:
      secretName: standup-endpoints-config
  - name: kubeconfig
    secret:
      secretName: standup-kubeconfig
  workspaces:
  - name: cluster
    description: Cluster information is stored here.
  params:
  - name: release-id
    description: The release version to use when creating the cluster.
    default: s3-bucket-credentials-secret
  steps:
  - name: create-cluster-stable
    image: quay.io/giantswarm/standup:2.1.0
    volumeMounts:
      - name: endpoints-config
        mountPath: /etc/endpoints-config
      - name: kubeconfig
        mountPath: /etc/kubeconfig
    script: |
      #! /bin/sh
      LATEST_STABLE_RELEASE=`find /workspace/releases/azure -regex 'azure/v[0-9]*\.[0-9]*\.[0-9]*' | sort | tail -n1`
      standup create cluster \
      --config /etc/endpoints-config/config \
      --release ${LATEST_STABLE_RELEASE#"azure/"} \
      --provider $(cat $(workspaces.cluster.path)/provider) \
      --output $(workspaces.cluster.path)
