apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: create-cluster
  namespace: test-workloads
  labels:
    app.kubernetes.io/name: "standup"
spec:
  volumes:
  - name: endpoints-config
    secret:
      secretName: standup-endpoints-config
  - name: kubeconfig
    secret:
      secretName: standup-kubeconfig
  workspaces:
  - name: cluster
    description: Cluster information is stored here.
  params:
  - name: release-id
    type: string
    description: Release ID to use when creating the cluster.
  results:
  - name: cluster-id
    description: The ID of the created cluster.
  steps:
  - name: create-cluster
    image: quay.io/giantswarm/standup:2.7.0
    volumeMounts:
      - name: endpoints-config
        mountPath: /etc/endpoints-config
      - name: kubeconfig
        mountPath: /etc/kubeconfig
    script: |
      #! /bin/sh
      standup create cluster \
      --config /etc/endpoints-config/config \
      --kubeconfig /etc/kubeconfig \
      --release $(params.release-id) \
      --installation $(cat $(workspaces.cluster.path)/installation) \
      --output $(workspaces.cluster.path)

      cat $(workspaces.cluster.path)/cluster-id > $(results.cluster-id.path)
