apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: create-cluster
  namespace: nightly
spec:
  resources:
    inputs:
    - name: releases
      type: git
  workspaces:
    - name: cluster
      description: a folder where to write the kubeconfig of the newly created cluster
  params:
  - name: wait_cluster_ready
    description: should the task wait for the cluster to be ready
    default: "true"
  - name: release_version
    description: release version from which to create the cluster
    default: "v12.1.0"
  steps:
  - name: create-cluster
    # This needs to become the image that has gsctl and standup commands
    image: busybox
    command: ["echo"]
    args:
    - "create"
    - "wait_cluster_ready"
    - ${inputs.params.wait_cluster_ready}
    - "release_version"
    - ${inputs.params.release_version}
