apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: create-cluster
  namespace: nightly
spec:
  resources:
    inputs:
    - name: releases
      type: git
  workspaces:
  - name: cluster
    description: The folder where to put the kubeconfig of the newly created cluster
  params:
  - name: gs-token-secret
    default: gs-token-secret
  steps:
  - name: create-cluster
    # This needs to become the image that has gsctl and standup commands
    image: quay.io/giantswarm/standup
    env:
    - name: TOKEN
      valueFrom:
        secretKeyRef:
          name: $(params.gs-token-secret)
          key: token
    args:
    - "create"
    - "--in-cluster"
    - "--token"
    - "${TOKEN}"
    - "--provider"
    - "aws"
    - "--endpoint"
    - "https://api.g8s.gaia.eu-central-1.aws.gigantic.io"
    - "--release"
    - "13.0.0"
    - "--releases"
    - "/workspace/releases"
    - "--output"
    - $(workspaces.cluster.path)/kubeconfig
