apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: create-release
  namespace: test-workloads
  labels:
    app.kubernetes.io/name: "standup"
spec:
  resources:
    inputs:
    - name: releases
      type: git
  volumes:
  - name: endpoints-config
    secret:
      secretName: standup-endpoints-config
  - name: kubeconfig
    secret:
      secretName: standup-kubeconfig
  workspaces:
  - name: cluster
    description: Cluster information is stored here.
  results:
  - name: release-id
    description: The ID of the created release.
  steps:
  - name: chown-releases
    command:
    - chown
    - -R
    - 1000:1000
    - /workspace
    image: quay.io/giantswarm/standup:2.7.0-92a782a3bd4beb761759784b5d8aba7589500b0e
    securityContext:
      runAsUser: 0
      runAsGroup: 0
  - name: create-release
    image: quay.io/giantswarm/standup:2.7.0-92a782a3bd4beb761759784b5d8aba7589500b0e
    volumeMounts:
      - name: endpoints-config
        mountPath: /etc/endpoints-config
      - name: kubeconfig
        mountPath: /etc/kubeconfig
    script: |
      #! /bin/sh
      standup create release \
      --config /etc/endpoints-config/config \
      --kubeconfig /etc/kubeconfig \
      --releases /workspace/releases \
      --output $(workspaces.cluster.path) \
      --task $(context.taskRun.name)

      cat $(workspaces.cluster.path)/release-id > $(results.release-id.path)
