apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: create-cluster-openstack
  namespace: test-workloads
spec:
  volumes:
  - name: kubeconfig
    secret:
      secretName: standup-kubeconfig
  workspaces:
  - name: cluster
    description: Cluster information is stored here.
  resources:
    inputs:
    - name: cluster-openstack
      type: git
  results:
  - name: cluster-id
    description: The ID of the created cluster.
  steps:
  - name: create-cluster
    image: quay.io/giantswarm/kubectl-gs:2.1.1-04a6d48d66560b0ff9dfb6aa27f216acda4aea5a
    volumeMounts:
      - name: kubeconfig
        mountPath: /etc/kubeconfig
    script: |
      #! /bin/sh

      set -e
      set -x

      export KUBECONFIG=/etc/kubeconfig/openstack

      # Generate template for control plane.
      kubectl-gs template cluster \
        --provider openstack \
        --organization multi-project \
        --description "e2e test" \
        --worker-failure-domain gb-lon-1 \
        --cloud openstack \
        --cloud-config cloud-config-giantswarm-2 \
        --bastion-image 8f0ccaf8-501e-4760-97cc-fbb8b812eb50 \
        --worker-image 857c9ff3-ac41-4aa3-bfde-2bb0cc4600f1 \
        --control-plane-image 857c9ff3-ac41-4aa3-bfde-2bb0cc4600f1 \
        --external-network-id cdbcb519-1f91-43fb-b0a9-312f0abf8f12 \
        --node-cidr 10.6.0.0/24 \
        --bastion-machine-flavor n1.tiny \
        --control-plane-machine-flavor n1.small \
        --worker-machine-flavor n1.small \
        --control-plane-disk-size 50 \
        --worker-disk-size 50 \
        --control-plane-az gb-lon-1 \
        --worker-replicas 2 \
        --bastion-boot-from-volume \
        --control-plane-boot-from-volume \
        --worker-boot-from-volume \
        --output /tmp/cluster.yaml

      # Extract cluster name from template.
      cluster_id=$(cat /tmp/cluster.yaml | grep cluster.x-k8s.io/cluster-name | head -n1 | cut -d" " -f6)

      echo -n "${cluster_id}" >$(workspaces.cluster.path)/cluster-id
      echo -n "${cluster_id}" > $(results.cluster-id.path)

      kubectl apply -f /tmp/cluster.yaml

  - name: capi-get-kubeconfig
    image: quay.io/giantswarm/clusterctl:v1.0.2
    volumeMounts:
      - name: kubeconfig
        mountPath: /etc/kubeconfig
    script: |
      #! /bin/sh

      export KUBECONFIG=/etc/kubeconfig/$(cat $(workspaces.cluster.path)/installation)
      for i in $(seq 1 20); do
        clusterctl -n org-giantswarm get kubeconfig $(cat $(workspaces.cluster.path)/cluster-id) >$(workspaces.cluster.path)/kubeconfig
        success=$?
        if [ "$success" -eq "0" ]; then
          break
        fi
        sleep 5
      done
      exit $success
