apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: e2e
  namespace: test-workloads
spec:
  workspaces:
    - name: cluster
      description: Cluster information is stored here.
  params:
  - name: test-deletion
    type: string
    description: Whether or not test deletion of clusters.
    default: "1"
  - name: plugin-branch
    type: string
    description: Branch of the plugin repository to use.
    default: "master"
  - name: PROVIDER
    type: string
    default: ""
    description: Name of the provider (either 'aws' or 'azure')
  - name: MC_KUBECONFIG
    type: string
    description: "Path of kubeconfig file to access test management cluster"
  steps:
    - name: download-sonobuoy-plugin
      image: alpine
      script: |
        #!/bin/sh

        for i in $(seq 1 5); do
          wget -O $(workspaces.cluster.path)/giantswarm-plugin.yaml https://raw.githubusercontent.com/giantswarm/sonobuoy-plugin/$(params.plugin-branch)/giantswarm-plugin.yaml
          success=$?
          if [ "$success" -eq "0" ]; then
            exit 0
          fi
          sleep 5
        done

        exit 1
    - name: run-tests
      image: quay.io/giantswarm/sonobuoy:v0.56.17-alpine-giantswarm
      env:
        - name: PROVIDER
          value: $(params.PROVIDER)
        - name: MC_KUBECONFIG
          value: $(params.MC_KUBECONFIG)
        - name: WC_KUBECONFIG
          value: "$(workspaces.cluster.path)/kubeconfig"
        - name: TEST_DELETION
          value: $(params.test-deletion)
        - name: CLUSTER_ID_PATH
          value: $(workspaces.cluster.path)/cluster-id
      script: |
        #! /bin/sh
        /sonobuoy run \
            --kubeconfig "${MC_KUBECONFIG}" \
            --namespace "$(cat "${CLUSTER_ID_PATH}")-sonobuoy" \
            --plugin $(workspaces.cluster.path)/giantswarm-plugin.yaml \
            --plugin-env giantswarm.TC_KUBECONFIG="$(cat "${WC_KUBECONFIG}")" \
            --plugin-env giantswarm.CP_KUBECONFIG="$(cat "${MC_KUBECONFIG}")" \
            --plugin-env giantswarm.CLUSTER_ID="$(cat "${CLUSTER_ID_PATH}")" \
            --plugin-env giantswarm.PROVIDER="${PROVIDER}" \
            --plugin-env giantswarm.TEST_DELETION="${TEST_DELETION}" \
            --mode=certified-conformance \
            --wait
      volumeMounts:
        - mountPath: /etc/kubeconfig
          name: kubeconfig
  volumes:
    - name: kubeconfig
      secret:
        secretName: sonobuoy-kubeconfig
