apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: e2e
  namespace: test-workloads
spec:
  workspaces:
    - name: cluster
      description: Cluster information is stored here.
  params:
  - name: test-deletion
    type: string
    description: Whether or not test deletion of clusters.
    default: "1"
  - name: plugin-branch
    type: string
    description: Branch of the plugin repository to use.
    default: "master"
  - name: PROVIDER
    type: string
    default: ""
    description: Name of the provider (either 'aws' or 'azure')
  - name: MC_KUBECONFIG
    type: string
    description: "Path of kubeconfig file to access test management cluster"
  steps:
    - name: run-tests
      image: quay.io/giantswarm/sonobuoy-plugin:latest
      env:
        - name: PROVIDER
          value: $(params.PROVIDER)
        - name: CP_KUBECONFIG_PATH
          value: $(params.MC_KUBECONFIG)
        - name: TC_KUBECONFIG_PATH
          value: "$(workspaces.cluster.path)/kubeconfig"
        - name: TEST_DELETION
          value: $(params.test-deletion)
        - name: CLUSTER_ID_PATH
          value: $(workspaces.cluster.path)/cluster-id
      script: |
        #!/bin/sh
        export CLUSTER_ID="$(cat $CLUSTER_ID_PATH)"
        export CP_KUBECONFIG="$(cat $CP_KUBECONFIG_PATH)"
        export TC_KUBECONFIG="$(cat $TC_KUBECONFIG_PATH)"
        /app/run_go_test.sh

        if [ $? -ne 0 ]
        then
          echo "e2e tests failed"
          exit 1
        fi
      volumeMounts:
        - mountPath: /etc/kubeconfig
          name: kubeconfig
  volumes:
    - name: kubeconfig
      secret:
        secretName: sonobuoy-kubeconfig
