apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: generate-workload-cluster-kubeconfig
  namespace: test-workloads
  labels:
    app.kubernetes.io/name: "standup"
spec:
  workspaces:
  - name: cluster
    description: Cluster information is stored here.
  params:
  - name: cluster-id
    description: ID of the workload cluster to use
  volumes:
  - name: kubeconfig
    secret:
      secretName: standup-kubeconfig
  steps:
  - name: generate-workload-cluster-kubeconfig
    image: quay.io/giantswarm/devctl:4.1.0
    volumeMounts:
    - name: kubeconfig
      mountPath: /etc/kubeconfig
    script: |
      #! /bin/sh
      set -e

      echo -n "$(params.cluster-id)" > $(workspaces.cluster.path)/cluster-id
      devctl gen kubeconfig --clusterID $(params.cluster-id) --kubeconfig /etc/kubeconfig/azure --output $(workspaces.cluster.path)/kubeconfig
