apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: get-latest-release
  namespace: test-workloads
spec:
  volumes:
    - name: kubeconfig
      secret:
        secretName: standup-kubeconfig
  workspaces:
    - name: cluster
      description: Cluster information is stored here.
  params:
    - name: kubeconfig-path
      type: string
      description: Kubeconfig path for the Management Cluster containing releases.
  results:
    - name: release-id
      description: The ID of the latest release.
  steps:
    - name: get-latest-release
      image: quay.io/giantswarm/standup:3.3.0
      volumeMounts:
        - name: kubeconfig
          mountPath: /etc/kubeconfig
      script: |
        #! /bin/sh
        LATEST_STABLE_RELEASE=$(kubectl --kubeconfig $(params.kubeconfig-path) get releases -o json | jq -r '[.items | sort_by(.metadata.name) | reverse[] | select(.metadata.name | test("v1[0-9]*\\.[0-9]*\\.[0-9]*$")) ][].metadata.name' | head -n1)

        echo -n ${LATEST_STABLE_RELEASE} > $(results.release-id.path)
