apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: gsctl-create-cluster
  namespace: test-workloads
spec:
  params:
    - name: name
      type: string
  volumes:
  - name: endpoints-config
    secret:
      secretName: standup-endpoints-config
  workspaces:
  - name: cluster
    description: Cluster information is stored here.
  steps:
  - name: deploy
    image: quay.io/giantswarm/standup:3.2.0
    volumeMounts:
      - name: endpoints-config
        mountPath: /etc/endpoints-config
    script: |
      #! /bin/sh
      set -x
      gsctl create cluster \
      -o giantswarm \
      -n $(params.name)
