apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello-world
  namespace: test-workloads
spec:
  volumes:
  - name: endpoints-config
    secret:
      secretName: standup-endpoints-config
  - name: kubeconfig
    secret:
      secretName: standup-kubeconfig
  workspaces:
  - name: cluster
    description: Cluster information is stored here.
  steps:
    - name: echo
      image: ubuntu
      command:
        - sh
      args:
        - -c
        - date; echo sleeping; sleep 1d
