apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello-world
  namespace: test-workloads
spec:
  steps:
    - name: echo
      image: ubuntu
      command:
        - echo
      args:
        - "Hello World"
