apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: create-cluster-kgs
  namespace: test-workloads
  labels:
    app.kubernetes.io/name: "standup"
spec:
  volumes:
  - name: endpoints-config
    secret:
      secretName: standup-endpoints-config
  - name: kubeconfig
    secret:
      secretName: standup-kubeconfig
  workspaces:
  - name: cluster
    description: Cluster information is stored here.
  params:
  - name: cluster-id
    description: ID of the cluster that will be created.
  - name: region
    description: Cloud region where to create the resources.
  - name: organization
    default: giantswarm
    description: Organization owning the cluster.
  - name: master-az
    description: Tenant master availability zone.
  - name: availability-zones
    description: List of availability zones to use, instead of setting a number. Use comma to separate values.
  - name: nodex-max
    default: 3
    description: Maximum number of worker nodes for the node pool.
  - name: nodex-min
    default: 3
    description: Minimum number of worker nodes for the node pool.
  steps:
  - name: render-cluster-manifests
    image: quay.io/giantswarm/standup:2.7.0-92a782a3bd4beb761759784b5d8aba7589500b0e
    volumeMounts:
      - name: endpoints-config
        mountPath: /etc/endpoints-config
      - name: kubeconfig
        mountPath: /etc/kubeconfig
    script: |
      #! /bin/sh
      standup create clusterkgs \
      --config /etc/endpoints-config/config \
      --release $(cat $(workspaces.cluster.path)/release-id) \
      --provider $(cat $(workspaces.cluster.path)/provider) \
      --cluster-id "$(params.cluster-id)" \
      --region "$(params.region)" \
      --organization "$(params.organization)" \
      --master-az "$(params.master-az)" \
      --availability-zones "$(params.availability-zones)" \
      --nodex-max $(params.nodex-max) \
      --nodex-min $(params.nodex-min) \
      --output $(workspaces.cluster.path)

  - name: create-cluster
    image: bitnami/kubectl:1.18
    args: [
      "apply",
      "-f",
      "$(workspaces.cluster.path)/manifests.yaml"
    ]
