apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: opsctl-deploy
  namespace: test-workloads
spec:
  volumes:
  - name: kubeconfig
    secret:
      secretName: standup-kubeconfig
  workspaces:
  - name: cluster
    description: Cluster information is stored here.
  steps:
  - name: deploy
    image: quay.io/giantswarm/opsctl:1.29.0-00425306b6dc81715bed30e3ad1b2e117d54faaf
    volumeMounts:
      - name: kubeconfig
        mountPath: /etc/kubeconfig
    env:
      - name: KUBECONFIG
        value: /etc/kubeconfig/aws
      - name: OPSCTL_UNSAFE_FORCE_VERSION
        value: 1.29.1-dev
      - name: OPSCTL_GITHUB_TOKEN
        valueFrom:
          secretKeyRef:
            name: tityosbot-token-github
            key: oauth
    script: |
      #! /bin/sh
      opsctl deploy \
      --use-kubeconfig \
      prometheus-meta-operator@v1.51.1
