apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: save-sonobuoy-results
  namespace: test-workloads
spec:
  workspaces:
    - name: cluster
      description: Cluster information is stored here.
  params:
    - name: kubeconfig-path
      type: string
      description: Kubeconfig path for the cluster where sonobuoy will run.
    - name: results-path
      type: string
      description: Path where results will be stored.
      default: "$(workspaces.cluster.path)/sonobuoy-results.tar"
    - name: sonobuoy-namespace
      type: string
      description: Namespace that sonobuoy will create to store its resources.
      default: "sonobuoy"
  steps:
    - name: save-sonobuoy-results
      image: sonobuoy/sonobuoy:v0.52.0
      env:
        - name: "KUBECONFIG_PATH"
          value: $(workspaces.cluster.path)/kubeconfig
      command: 
        - "/sonobuoy"
      args:
        - retrieve
        - $(params.results-path)
        - --namespace 
        - $(params.sonobuoy-namespace)
        - --kubeconfig
        - $(workspaces.cluster.path)/kubeconfig
      volumeMounts:
        - mountPath: /etc/kubeconfig
          name: kubeconfig
  volumes:
    - name: kubeconfig
      secret:
        secretName: sonobuoy-kubeconfig
