apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: upgrade-cluster
  namespace: test-workloads
spec:
  workspaces:
  - name: cluster
    description: Cluster information is stored here.
  steps:
  - name: upgrade-cluster
    image: quay.io/giantswarm/standup:2.3.0
    script: |
      #! /bin/sh
      echo "Upgrading cluster $(cat $(workspaces.cluster.path)/cluster-id) to $(cat $(workspaces.cluster.path)/release-id)"
      kubectl --kubeconfig /etc/kubeconfig/azure -n$(kubectl --kubeconfig /etc/kubeconfig/azure get clusters -A | grep $(cat $(workspaces.cluster.path)/cluster-id) | awk '{print $1}') patch cluster/$(cat $(workspaces.cluster.path)/cluster-id) -p '{"metadata":{"labels":{"release.giantswarm.io/version": "$(cat $(workspaces.cluster.path)/release-id)"}}}' --type=merge
