apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: upload-to-s3-bucket
  namespace: nightly
spec:
  workspaces:
  - name: cluster
    description: Cluster information is stored here.
  params:
  - name: prow-job-id
    description: ID of the prow job of this task
  - name: s3-bucket-name
    default: automated-test-results.giantswarm.io
  - name: s3-bucket-credentials-secret
    default: s3-bucket-credentials-secret
  - name: file-to-upload
    description: The path to the file that needs to get uploaded to the s3 bucket.
  steps:
  - name: upload-to-s3-bucket
    image: amazon/aws-cli:2.0.24
    env:
      - name: "AWS_ACCESS_KEY_ID"
        valueFrom:
          secretKeyRef:
            name: $(params.s3-bucket-credentials-secret)
            key: access-key-id
      - name: "AWS_DEFAULT_REGION"
        valueFrom:
          secretKeyRef:
            name: $(params.s3-bucket-credentials-secret)
            key: default-region
      - name: "AWS_SECRET_ACCESS_KEY"
        valueFrom:
          secretKeyRef:
            name: $(params.s3-bucket-credentials-secret)
            key: secret-access-key
    script: |
      #! /bin/sh
      aws s3 cp "$(params.file-to-upload)" s3://$(params.s3-bucket-name)/"$(params.prow-job-id)"/"$(params.file-to-upload)"
      file_link="https://s3.console.aws.amazon.com/s3/object/$(params.s3-bucket-name)/$(params.prow-job-id)/$(params.file-to-upload)"
      echo "You can download the results in the next week here: ${file_link}"
