apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: wait-for-ready
  namespace: test-workloads
  labels:
    app.kubernetes.io/name: "standup"
spec:
  workspaces:
  - name: cluster
    description: Cluster information is stored here.
  steps:
  - name: wait-for-ready
    image: quay.io/giantswarm/standup:2.0.0-ef1d4de6f1a2c4aa6b14efa4f3180afaa94c27ab
    script: |
      #! /bin/sh
      standup wait \
      --kubeconfig $(workspaces.cluster.path)/kubeconfig \
      --provider $(cat $(workspaces.cluster.path)/provider)
