apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: wait-for-ready
  namespace: test-workloads
  labels:
    app.kubernetes.io/name: "standup"
spec:
  params:
  - name: kubeconfig
    type: string
    description: Kubeconfig of the created cluster.
  - name: provider
    type: string
    description: Provider of the created cluster.
  steps:
  - name: wait-for-ready
    image: quay.io/giantswarm/standup:3.0.0
    script: |
      #! /bin/sh
      echo $(params.kubeconfig) > /tmp/kubeconfig

      standup wait \
      --kubeconfig /tmp/kubeconfig \
      --provider $(params.provider)
