apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: wait-for-ready
  namespace: test
spec:
  workspaces:
  - name: cluster
    description: Cluster information is stored here.
  steps:
  - name: wait-for-ready
    image: quay.io/giantswarm/standup
    script: |
      #! /bin/sh
      standup wait \
      --kubeconfig $(workspaces.cluster.path)/kubeconfig
