apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: wait-for-ready
  namespace: test-workloads
  labels:
    app.kubernetes.io/name: "standup"
spec:
  workspaces:
  - name: cluster
    description: Cluster information is stored here.
  steps:
  - name: wait-for-ready
    image: quay.io/giantswarm/standup:1.1.0
    script: |
      #! /bin/sh
      standup wait \
      --kubeconfig $(workspaces.cluster.path)/kubeconfig
