apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: wait-for-condition-ready
  namespace: test-workloads
spec:
  volumes:
    - name: kubeconfig
      secret:
        secretName: standup-kubeconfig
  workspaces:
    - name: cluster
      description: Cluster information is stored here.
  params:
  - name: cluster-id
    type: string
    description: Cluster ID for the cluster that we want to wait for.
  - name: kubeconfig-path
    type: string
    description: Kubeconfig path for the cluster where sonobuoy will run.
  steps:
    - name: wait-for-condition-ready
      image: quay.io/giantswarm/standup:3.0.0
      volumeMounts:
        - name: kubeconfig
          mountPath: /etc/kubeconfig
      script: |
        #! /bin/sh

        set -eo pipefail

        CLUSTER_NAMESPACE=$(kubectl --kubeconfig $(params.kubeconfig-path) get clusters -A | grep $(params.cluster-id) | awk '{print $1}')

        # Wait for the cluster to be ready
        while ! kubectl --kubeconfig $(params.kubeconfig-path) get clusters -n${CLUSTER_NAMESPACE} $(params.cluster-id) -o json | jq -e '.status.conditions[] | select(.type=="Ready" and .status=="True")'>/dev/null
        do
          echo "$(date): Cluster '$(params.cluster-id)' is not Ready yet"
          sleep 10
        done

        echo "$(date): Cluster $(params.cluster-id) is Ready"

        # Wait for the cluster to be completely created
        while ! kubectl --kubeconfig $(params.kubeconfig-path) get clusters -n${CLUSTER_NAMESPACE} $(params.cluster-id) -o json | jq -e '.status.conditions[] | select(.type=="Creating" and .status=="False")'>/dev/null
        do
          echo "$(date): Cluster '$(params.cluster-id)' is still creating"
          sleep 10
        done

        echo "$(date): Cluster $(params.cluster-id) has finished creating"
