version: 2.1

orbs:
  architect: giantswarm/architect@4.26.0

jobs:
  build:
    docker:
      - image: quay.io/giantswarm/architect:6.5.0
    steps:
      - checkout
      - run:
          name: Install kustomize
          command: |
            curl -s -O -L https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv3.8.4/kustomize_v3.8.4_linux_amd64.tar.gz
            tar xzf ./kustomize_v*_*_amd64.tar.gz
            ./kustomize version
      - run:
          name: Kustomize helm charts
          command: |
            for i in prow tekton; do mkdir -p helm/test-infra/templates; ./kustomize build ./$i > helm/test-infra/templates/$i.yaml; done
      - persist_to_workspace:
          root: .
          paths:
            - helm

workflows:
  version: 2
  workflow:
    jobs:
      - build:
          filters:
            # Trigger job also on git tag.
            tags:
              only: /^v.*/
      - architect/push-to-app-catalog:
          context: architect
          name: push-to-app-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          attach_workspace: true
          chart: test-infra
          requires:
            - build
          filters:
            # Trigger job also on git tag.
            tags:
              only: /^v.*/
