apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: ghproxy
  labels:
    app: ghproxy
spec:
  privileged: false
  runAsUser:
    rule: MustRunAsNonRoot
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  hostPID: false
  hostIPC: false
  hostNetwork: false
  volumes:
    - 'persistentVolumeClaim'
    - 'secret'
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  readOnlyRootFilesystem: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ghproxy-psp
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - ghproxy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ghproxy-psp
roleRef:
  kind: ClusterRole
  name: ghproxy-psp
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: ghproxy
  namespace: test-infra
---
kind: ServiceAccount
apiVersion: v1
metadata:
  namespace: test-infra
  name: "ghproxy"
