kind: ServiceAccount
apiVersion: v1
metadata:
  namespace: nightly
  name: releases
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: nightly
  name: releases
rules:
  - apiGroups:
      - release.giantswarm.io
    resources:
      - "*"
    verbs:
      - "*"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: nightly
  name: releases
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: releases
subjects:
  - kind: ServiceAccount
    name: releases
    namespace: nightly
