apiVersion: v1
kind: Namespace
metadata:
  name: test-workloads
---
kind: ServiceAccount
apiVersion: v1
metadata:
  namespace: test-workloads
  name: test-runs
imagePullSecrets:
- name: pull-secret
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: test-workloads
  name: release-manager
rules:
  - apiGroups:
      - release.giantswarm.io
    resources:
      - "*"
    verbs:
      - "*"
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: test-workloads
  name: secret-manager
rules:
  - apiGroups:
      - ""
    resources:
      - "secrets"
    verbs:
      - get
      - list
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: test-workloads
  name: release-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: release-manager
subjects:
  - kind: ServiceAccount
    name: test-runs
    namespace: test-workloads
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: test-workloads
  name: secret-manager-test-runs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secret-manager
subjects:
  - kind: ServiceAccount
    name: test-runs
    namespace: test-workloads
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: test-runs
spec:
  allowPrivilegeEscalation: false
  fsGroup:
    ranges:
    - max: 65535
      min: 1
    rule: MustRunAs
  # create-cluster task needs root in order to chown
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - persistentVolumeClaim
  - secret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: test-runs-psp
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - test-runs
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: test-runs-psp
roleRef:
  kind: ClusterRole
  name: test-runs-psp
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: test-runs
  namespace: test-workloads
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: affinity-assistant
spec:
  allowPrivilegeEscalation: false
  fsGroup:
    ranges:
    - max: 65535
      min: 1
    rule: MustRunAs
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - configMap
  - persistentVolumeClaim
  - secret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: affinity-assistant-psp
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - affinity-assistant
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: affinity-assistant-psp
roleRef:
  kind: ClusterRole
  name: affinity-assistant-psp
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  # Cannot change service account of affinity assistant
  # https://github.com/tektoncd/pipeline/issues/3020
  name: default
  namespace: test-workloads
