apiVersion: v1
kind: Namespace
metadata:
  name: test-workloads
---
kind: ServiceAccount
apiVersion: v1
metadata:
  namespace: test-workloads
  name: test-runs
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: test-workloads
  name: release-manager
rules:
  - apiGroups:
      - release.giantswarm.io
    resources:
      - "*"
    verbs:
      - "*"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: test-workloads
  name: release-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: release-manager
subjects:
  - kind: ServiceAccount
    name: test-runs
    namespace: test-workloads
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: test-runs
spec:
  fsGroup:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - persistentVolumeClaim
  - secret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: test-runs-psp
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - test-runs
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: test-runs-psp
roleRef:
  kind: ClusterRole
  name: test-runs-psp
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: test-runs
  namespace: test-workloads
