apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: aws-full
  namespace: test-workloads
spec:
  resources:
  - name: releases
    type: git
  params:
  - name: PROW_JOB_ID
    type: string
  tasks:
  - name: create-release
    params:
    - name: pipeline-name
      value: "$(context.pipeline.name)"
    taskRef:
      name: create-release
    resources:
      inputs:
      - name: releases
        resource: releases

  - name: test-pl002
    runAfter: [create-release]
    timeout: 2h0m0s
    taskRef:
      name: aws-cnfm
    params:
      - name: cnfm-plan
        value: pl002
      - name: release-id
        value: "$(tasks.create-release.results.release-id)"

  - name: test-pl003
    runAfter: [create-release]
    timeout: 2h0m0s
    taskRef:
      name: aws-cnfm
    params:
      - name: cnfm-plan
        value: pl003
      - name: release-id
        value: "$(tasks.create-release.results.release-id)"

  - name: test-pl004
    runAfter: [create-release]
    timeout: 2h0m0s
    taskRef:
      name: aws-cnfm
    params:
      - name: cnfm-plan
        value: pl003
      - name: release-id
        value: "$(tasks.create-release.results.release-id)"

  - name: test-pl005
    runAfter: [create-release]
    timeout: 2h0m0s
    taskRef:
      name: aws-cnfm
    params:
      - name: cnfm-plan
        value: pl003
      - name: release-id
        value: "$(tasks.create-release.results.release-id)"

  finally:
  - name: cleanup-pl002
    taskRef:
      name: cleanup
    params:
      - name: cluster-id
        value: "$(tasks.test-pl002.results.cluster-id)"
      - name: release-id
        value: "$(tasks.create-release.results.release-id)"
      - name: installation
        value: "$(tasks.create-release.results.installation)"
  - name: cleanup-pl003
    taskRef:
      name: cleanup
    params:
      - name: cluster-id
        value: "$(tasks.test-pl003.results.cluster-id)"
      - name: release-id
        value: "$(tasks.create-release.results.release-id)"
      - name: installation
        value: "$(tasks.create-release.results.installation)"
  - name: cleanup-pl004
    taskRef:
      name: cleanup
    params:
      - name: cluster-id
        value: "$(tasks.test-pl003.results.cluster-id)"
      - name: release-id
        value: "$(tasks.create-release.results.release-id)"
      - name: installation
        value: "$(tasks.create-release.results.installation)"
  - name: cleanup-pl005
    taskRef:
      name: cleanup
    params:
      - name: cluster-id
        value: "$(tasks.test-pl003.results.cluster-id)"
      - name: release-id
        value: "$(tasks.create-release.results.release-id)"
      - name: installation
        value: "$(tasks.create-release.results.installation)"