apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: aws
  namespace: test-workloads
spec:
  resources:
  - name: releases
    type: git
  params:
  - name: PROW_JOB_ID
    type: string
  tasks:
  - name: create-release
    params:
    - name: pipeline-name
      value: "$(context.pipeline.name)"
    taskRef:
      name: create-release
    resources:
      inputs:
      - name: releases
        resource: releases

  - name: test-aws
    runAfter: [create-release]
    timeout: 2h0m0s
    taskRef:
      name: aws-cnfm
    params:
      - name: cnfm-plan
        value: pl001
      - name: release-id
        value: "$(tasks.create-release.results.release-id)"

  finally:
  - name: cleanup
    taskRef:
      name: cleanup
    params:
      - name: cluster-id
        value: "$(tasks.test-aws.results.cluster-id)"
      - name: release-id
        value: "$(tasks.create-release.results.release-id)"
      - name: installation
        value: "$(tasks.create-release.results.installation)"