apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: aws
  namespace: test-workloads
spec:
  resources:
  - name: releases
    type: git
  workspaces:
  - name: cluster
  tasks:
  - name: create-release
    taskRef:
      name: aws
    workspaces:
    - name: cluster
      workspace: cluster
