apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: azure-upgrade
  namespace: test-workloads
spec:
  resources:
  - name: releases
    type: git
  workspaces:
  - name: cluster
  params:
  - name: PROW_JOB_ID
    type: string
  tasks:
  - name: create-cluster-latest
    taskRef:
      name: create-cluster-latest
    workspaces:
      - name: cluster
        workspace: cluster

  - name: create-release
    runAfter: [create-cluster-latest]
    taskRef:
      name: create-release
    workspaces:
      - name: cluster
        workspace: cluster
    resources:
      inputs:
        - name: releases
          resource: releases

  - name: wait-for-ready
    runAfter: [create-cluster-latest]
    timeout: 1h0m0s
    taskRef:
      name: wait-for-ready
    workspaces:
      - name: cluster
        workspace: cluster

  - name: upgrade-cluster
    runAfter: [wait-for-ready]
    taskRef:
      name: upgrade-cluster
    workspaces:
    - name: cluster
      workspace: cluster

  - name: test-azure
    runAfter: [wait-for-ready]
    taskRef:
      name: azure
    workspaces:
    - name: cluster
      workspace: cluster

  finally:
  - name: cleanup
    taskRef:
      name: cleanup
    workspaces:
      - name: cluster
        workspace: cluster
