apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: cis
  namespace: nightly
spec:
  workspaces:
    - name: cluster
  resources:
  - name: releases
    type: git
  tasks:
  - name: create-cluster
    taskRef:
      name: create-cluster
    workspaces:
    - name: cluster
      workspace: cluster
    resources:
      inputs:
      - name: releases
        resource: releases
    params:
    - name: wait_cluster_ready
      value: "true"
    - name: release_version
      value: "v12.1.0"

  - name: run-tests
    runAfter: [create-cluster]
    taskRef:
      name: cis
    workspaces:
    - name: cluster
      workspace: cluster

  - name: cleanup
    runAfter: [run-tests]
    taskRef:
      name: cleanup
    workspaces:
    - name: cluster
      workspace: cluster
