apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cis
  namespace: nightly
spec:
  resources:
  - name: releases
    type: git
  workspaces:
  - name: cluster
  tasks:
  - name: create-cluster
    taskRef:
      name: create-cluster
    workspaces:
    - name: cluster
      workspace: cluster
    resources:
      inputs:
      - name: releases
        resource: releases

  - name: run-tests
    runAfter: [create-cluster]
    taskRef:
      name: cis
    workspaces:
    - name: cluster
      workspace: cluster

  finally:
  - name: cleanup
    taskRef:
      name: cleanup
    workspaces:
    - name: cluster
      workspace: cluster
