apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: cis
  namespace: nightly
spec:
  resources:
  - name: releases
    type: git
    params:
      - name: depth
        value: 0
  workspaces:
    - name: cluster
  tasks:
  - name: create-cluster
    taskRef:
      name: create-cluster
    workspaces:
    - name: cluster
      workspace: cluster
    resources:
      inputs:
      - name: releases
        resource: releases

  - name: run-tests
    runAfter: [create-cluster]
    taskRef:
      name: cis
    workspaces:
    - name: cluster
      workspace: cluster

  - name: cleanup
    runAfter: [run-tests]
    taskRef:
      name: cleanup
    workspaces:
    - name: cluster
      workspace: cluster
