apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: cncf
  namespace: nightly
spec:
  resources:
  - name: releases
    type: git
  tasks:
  - name: create-cluster
    taskRef:
      name: create-cluster
    resources:
      inputs:
      - name: releases
        resource: releases
    params:
    - name: wait_cluster_ready
      value: "true"
    - name: release_version
      value: "v12.1.0"

  - name: run-tests
    runAfter: [create-cluster]
    timeout: 5h0m0s
    taskRef:
      name: cncf

  - name: cleanup
    runAfter: [run-tests]
    taskRef:
      name: cleanup
