apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cncf
  namespace: test
spec:
  resources:
  - name: releases
    type: git
  workspaces:
  - name: cluster
  tasks:
  - name: create-cluster
    taskRef:
      name: create-cluster
    workspaces:
    - name: cluster
      workspace: cluster
    resources:
      inputs:
      - name: releases
        resource: releases

  - name: wait-for-ready
    runAfter: [create-cluster]
    taskRef:
      name: wait-for-ready
    workspaces:
      - name: cluster
        workspace: cluster

  - name: run-tests
    runAfter: [wait-for-ready]
    timeout: 5h0m0s
    taskRef:
      name: cncf
    workspaces:
    - name: cluster
      workspace: cluster

  finally:
  - name: cleanup
    taskRef:
      name: cleanup
    workspaces:
    - name: cluster
      workspace: cluster
