apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: create-cluster-capi-pure
  namespace: test-workloads
spec:
  resources:
  - name: source-repo
    type: git
  workspaces:
  - name: cluster
  params:
  - name: PROW_JOB_ID
    type: string
  - name: REPO_NAME
    type: string
  - name: provider
    type: string
  - name: installation
    type: string
  - name: cluster-catalog
    type: string
  - name: cluster-chart
    type: string
  - name: default-apps-catalog
    type: string
  - name: default-apps-chart
    type: string
  tasks:
  - name: create-cluster
    params:
    - name: provider
      value: $(params.provider)
    - name: installation
      value: $(params.installation)
    - name: repo-name
      value: $(params.repo-name)
    - name: cluster-chart
      value: $(params.cluster-chart)
    - name: cluster-catalog
      value: $(params.cluster-catalog)
    - name: default-apps-chart
      value: $(params.default-apps-chart)
    - name: default-apps-catalog
      value: $(params.default-apps-catalog)
    taskRef:
      name: create-cluster-capi-pure
    workspaces:
      - name: cluster
        workspace: cluster
    resources:
      inputs:
      - name: source-repo
        resource: source-repo

  - name: wait-for-ready
    runAfter: [create-cluster]
    timeout: 1h0m0s
    taskRef:
      name: wait-for-ready
    workspaces:
      - name: cluster
        workspace: cluster

  finally:
  - name: cleanup
    taskRef:
      name: cleanup-capi
    workspaces:
      - name: cluster
        workspace: cluster
