apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: gs
  namespace: test-workloads
spec:
  resources:
  - name: releases
    type: git
  workspaces:
  - name: cluster
  params:
  - name: PROW_JOB_ID
    type: string
  tasks:
  - name: create-release
    taskRef:
      name: create-release
    workspaces:
    - name: cluster
      workspace: cluster
    resources:
      inputs:
      - name: releases
        resource: releases

  - name: create-cluster
    runAfter: [create-release]
    taskRef:
      name: create-cluster
    workspaces:
    - name: cluster
      workspace: cluster

  - name: wait-for-ready
    runAfter: [create-cluster]
    timeout: 1h0m0s
    taskRef:
      name: wait-for-ready
    workspaces:
      - name: cluster
        workspace: cluster

  - name: run-tests
    runAfter: [wait-for-ready]
    timeout: 1h0m0s
    taskRef:
      name: gs
    workspaces:
    - name: cluster
      workspace: cluster

  finally:
  - name: cleanup
    taskRef:
      name: cleanup
    workspaces:
    - name: cluster
      workspace: cluster
