apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: heartbeat
  namespace: test-workloads
spec:
  workspaces:
    - name: cluster
  params:
    - name: PROW_JOB_ID
      type: string
    - name: PULL_PULL_SHA
      type: string
  tasks:
    - name: deploy-prometheus-meta-operator
      taskRef:
        name: opsctl-deploy
      params:
        - name: chart
          value: prometheus-meta-operator
        - name: ref
          value: "$(params.PULL_PULL_SHA)"
        - name: kubeconfig
          value: aws
      workspaces:
        - name: cluster
          workspace: cluster

    - name: get-latest-release
      taskRef:
        name: get-latest-release
      params:
        - name: kubeconfig-path
          value: "/etc/kubeconfig/aws"
      workspaces:
        - name: cluster
          workspace: cluster

    - name: create-cluster
      runAfter:
        - get-latest-release
        - deploy-prometheus-meta-operator
      taskRef:
        name: create-cluster
      params:
      - name: release-id
        value: "$(tasks.get-latest-release.results.release-id)"
      workspaces:
        - name: cluster
          workspace: cluster

    - name: wait-for-ready
      runAfter: [create-cluster]
      timeout: 1h0m0s
      taskRef:
        name: wait-for-ready
      workspaces:
        - name: cluster
          workspace: cluster

  finally:
    - name: undeploy-prometheus-meta-operator
      taskRef:
        name: opsctl-undeploy
      params:
        - name: chart
          value: prometheus-meta-operator
        - name: kubeconfig
          value: aws
      workspaces:
        - name: cluster
          workspace: cluster
