apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: heartbeat
  namespace: test-workloads
spec:
  workspaces:
    - name: cluster
  params:
    - name: PROW_JOB_ID
      type: string
  tasks:
    - name: hello-world
      taskRef:
        name: hello-world
      workspaces:
        - name: cluster
          workspace: cluster
