apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: heartbeat-runner
  namespace: test-workloads
spec:
  params:
    - name: PROW_JOB_ID
      type: string
  pipelineRef:
    name: heartbeat
  serviceAccountName: heartbeat-runner
