apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: upgrade-to-this-azure-operator
  namespace: test-workloads
spec:
  resources:
  - name: releases
    type: git
  - name: azure-operator
    type: git
  workspaces:
  - name: cluster
  params:
  - name: PROW_JOB_ID
    type: string
  tasks:
  - name: create-test-operator-release
    taskRef:
      name: create-test-operator-release
    workspaces:
    - name: cluster
      workspace: cluster
    resources:
      inputs:
      - name: releases
        resource: releases
      - name: azure-operator
        resource: azure-operator

  - name: get-latest-release
    runAfter: [create-test-operator-release]
    taskRef:
      name: get-latest-release
    params:
      - name: kubeconfig-path
        value: "/etc/kubeconfig/azure"
    workspaces:
      - name: cluster
        workspace: cluster

  - name: create-cluster
    runAfter: [get-latest-release]
    taskRef:
      name: create-cluster
    params:
    - name: release-id
      value: "$(tasks.get-latest-release.results.release-id)"
    workspaces:
      - name: cluster
        workspace: cluster

  - name: wait-for-condition-ready
    runAfter: [create-cluster]
    timeout: 1h0m0s
    taskRef:
      name: wait-for-condition-ready
    params:
      - name: cluster-id
        value: "$(tasks.create-cluster.results.cluster-id)"
      - name: kubeconfig-path
        value: "/etc/kubeconfig/azure"
    workspaces:
      - name: cluster
        workspace: cluster

  - name: upgrade-cluster
    runAfter: [wait-for-condition-ready]
    taskRef:
      name: upgrade-cluster
    params:
      - name: cluster-id
        value: "$(tasks.create-cluster.results.cluster-id)"
      - name: kubeconfig-path
        value: "/etc/kubeconfig/azure"
      - name: release-id
        value: "$(tasks.create-test-operator-release.results.release-id)"
    workspaces:
      - name: cluster
        workspace: cluster

  - name: test-azure
    runAfter: [upgrade-cluster]
    taskRef:
      name: azure
    params:
    - name: kubeconfig-path
      value: "/etc/kubeconfig/azure"
    workspaces:
    - name: cluster
      workspace: cluster

  - name: manage-sonobuoy-results
    runAfter: [test-azure]
    taskRef:
      name: manage-sonobuoy-results
    params:
      - name: kubeconfig-path
        value: "/etc/kubeconfig/azure"
      - name: sonobuoy-namespace
        value: "$(tasks.create-cluster.results.cluster-id)-sonobuoy"
    workspaces:
      - name: cluster
        workspace: cluster

  finally:
  - name: upload-to-s3-bucket # executed only when tests fail
    when:
      - input: $(tasks.manage-sonobuoy-results.status)
        operator: in
        values: ["Failed"]
    taskRef:
      name: upload-to-s3-bucket
    params:
      - name: prow-job-id
        value: "$(params.PROW_JOB_ID)"
      - name: file-to-upload
        value: $(workspaces.cluster.path)/sonobuoy-results.tar
    workspaces:
      - name: cluster
        workspace: cluster

  - name: cleanup
    taskRef:
      name: cleanup
    workspaces:
      - name: cluster
        workspace: cluster
