apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: upgrade-cluster-capi-pure
  namespace: test-workloads
spec:
  resources:
  - name: source-repo
    type: git
  workspaces:
  - name: cluster
  params:
  - name: source-repo-name
    type: string
  - name: provider
    type: string
  - name: installation
    type: string
  - name: cluster-chart
    type: string
  - name: default-apps-chart
    type: string
  tasks:
  - name: calculate-versions
    params:
    - name: source-repo-name
      value: $(params.source-repo-name)
    - name: provider
      value: $(params.provider)
    - name: installation
      value: $(params.installation)
    - name: cluster-chart
      value: $(params.cluster-chart)
    - name: default-apps-chart
      value: $(params.default-apps-chart)
    taskRef:
      name: calculate-versions
    workspaces:
    - name: cluster
      workspace: cluster
    resources:
      inputs:
      - name: source-repo
        resource: source-repo
  - name: create-cluster
    params:
    - name: source-repo-name
      value: $(params.source-repo-name)
    - name: provider
      value: $(params.provider)
    - name: installation
      value: $(params.installation)
    - name: cluster-chart
      value: $(params.cluster-chart)
    - name: cluster-app-chart-version
      value: ""
    - name: cluster-app-catalog
      value: "cluster"
    - name: default-apps-chart
      value: $(params.default-apps-chart)
    - name: default-apps-chart-version
      value: ""
    - name: default-apps-catalog
      value: "cluster"
    taskRef:
      name: create-cluster-capi-pure
    workspaces:
    - name: cluster
      workspace: cluster
    resources:
      inputs:
      - name: source-repo
        resource: source-repo

  - name: wait-for-ready
    runAfter: [create-cluster]
    timeout: 1h0m0s
    taskRef:
      name: wait-for-ready
    workspaces:
    - name: cluster
      workspace: cluster

  - name: upgrade-cluster
    runAfter: [wait-for-ready]
    taskRef:
      name: upgrade-cluster-capi-pure
    params:
    - name: cluster-id
      value: "$(tasks.create-cluster.results.cluster-id)"
    - name: cluster-app-chart-version
      value: "$(tasks.calculate-versions.results.cluster-app-chart-version)"
    - name: provider
      value: $(params.provider)
    - name: organization
      value: "$(tasks.create-cluster.results.organization)"
    workspaces:
      - name: cluster
        workspace: cluster

  - name: wait-for-ready-after-upgrade
    runAfter: [upgrade-cluster]
    timeout: 1h0m0s
    taskRef:
      name: wait-for-ready
    workspaces:
      - name: cluster
        workspace: cluster

  finally:
  - name: cleanup
    when:
    - input: $(tasks.status)
      operator: in
      values: ["Succeeded"]
    taskRef:
      name: cleanup-capi-pure
    params:
    - name: cluster-id
      value: $(tasks.create-cluster.results.cluster-id)
    - name: organization
      value: $(tasks.create-cluster.results.organization)
    workspaces:
    - name: cluster
      workspace: cluster
