#! /bin/sh
set -e

kubeconfig_path="${KUBECONFIG_PATH:-"/cluster/kubeconfig"}"

function log {
  echo "[$(date -u +%FT%TZ)]" "$@"
}

function run_cis {
  log "Running cis"
  sonobuoy run  \
    --kubeconfig "$kubeconfig_path" \
    --plugin https://raw.githubusercontent.com/vmware-tanzu/sonobuoy-plugins/master/cis-benchmarks/kube-bench-plugin.yaml \
    --plugin https://raw.githubusercontent.com/vmware-tanzu/sonobuoy-plugins/master/cis-benchmarks/kube-bench-master-plugin.yaml \
    --plugin-env kube-bench-master.KUBERNETES_VERSION=1.16 --plugin-env kube-bench-node.KUBERNETES_VERSION=1.16 \
    --wait
}

function run_cncf {
  log "Running cncf"
  sonobuoy run --kubeconfig "$kubeconfig_path" --mode=certified-conformance --wait
}

function cleanup {
  log "Deleting sonobuoy resources"
  sonobuoy delete --kubeconfig "$kubeconfig_path"  --all || true
}

trap cleanup EXIT

case "$1" in
  cis)
    run_cis
    ;;
  cncf)
    run_cncf
    ;;
  *)
    log "Unknown test mode: $1"
    exit 1
    ;;
esac


sonobuoy status --kubeconfig "$kubeconfig_path"

outfile=$(sonobuoy retrieve --kubeconfig "$kubeconfig_path")

log "Results summary"
sonobuoy results "$outfile"

log "Detailed results"
sonobuoy results "$outfile" --mode detailed | jq .
