#! /bin/sh
set -e

kubeconfig_path="${KUBECONFIG_PATH:-"/cluster/kubeconfig"}"

log() {
  echo "[$(date -u +%FT%TZ)]" "$@"
}

run_cis() {
  log "Running cis"
  sonobuoy run  \
    --kubeconfig "$kubeconfig_path" \
    --plugin https://raw.githubusercontent.com/vmware-tanzu/sonobuoy-plugins/master/cis-benchmarks/kube-bench-plugin.yaml \
    --plugin https://raw.githubusercontent.com/vmware-tanzu/sonobuoy-plugins/master/cis-benchmarks/kube-bench-master-plugin.yaml \
    --plugin-env kube-bench-master.KUBERNETES_VERSION=1.16 --plugin-env kube-bench-node.KUBERNETES_VERSION=1.16 \
    --wait
}

run_cncf() {
  log "Running cncf"
  sonobuoy run --kubeconfig "$kubeconfig_path" --mode=certified-conformance --wait
}

print_results() {
  log "Status"
  sonobuoy status --kubeconfig "$kubeconfig_path"

  outfile=$(sonobuoy retrieve --kubeconfig "$kubeconfig_path")

  log "Results summary"
  sonobuoy results "$outfile"

  log "Detailed results"
  sonobuoy results "$outfile" --mode detailed | jq -R 'fromjson? | select(.status)'
}

check_if_failed() {
  if sonobuoy status --kubeconfig "$kubeconfig_path" | grep failed > /dev/null; then
    log "Tests failed"
    exit 1
  fi
}

cleanup() {
  if [ $? != 0 ]; then
    log "Sonobuoy logs"
    sonobuoy logs --kubeconfig "$kubeconfig_path"
  fi

  log "Deleting sonobuoy resources"
  sonobuoy delete --kubeconfig "$kubeconfig_path"  --all --wait || true
}

trap cleanup INT TERM EXIT

case "$1" in
  cis)
    run_cis
    print_results
    ;;
  cncf)
    run_cncf
    print_results
    check_if_failed
    ;;
  *)
    log "Unknown test mode: $1"
    exit 1
    ;;
esac
