apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: github-listener-interceptor
  namespace: tekton-pipelines
spec:
  resources:
    kubernetesResource:
      spec:
        template:
          spec:
            serviceAccountName: tekton-triggers-example-sa
            containers:
              - resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 250m
                    memory: 64Mi
  triggers:
    - name: github-listener
      template:
        ref: github-template
      bindings:
        - kind: TriggerBinding
          ref: github-pr-binding
      interceptors:
        - ref:
            name: "github"
            kind: ClusterInterceptor
            apiVersion: triggers.tekton.dev
          params:
          - name: "secretRef"
            value:
              secretName: github-secret
              secretKey: secretToken
          - name: "eventTypes"
            value: ["issue_comment"]
        - ref:
            name: cel
          params:
            - name: "filter"
              value: body.repository.full_name.startsWith('giantswarm/') &&
              body.repository.name in ['sonobuoy-plugin'] &&
              'pull_request' in body.issue &&
              'url' in body.issue.pull_request &&
              body.issue.state == 'open' &&
              body.comment.body.matches('^/test($| [^]*[ ]*$)')
            - name: "overlays"
              value:
              - key: add_pr_body.pull_request_url
                expression: body.issue.pull_request.url
        - webhook:
            objectRef:
              apiVersion: v1
              kind: Service
              name: add-pr-body
              namespace: tekton-pipelines
        - ref:
            name: cel
          params:
            - name: "overlays"
              value:
              - key: git_clone_depth
                expression: "string(body.extensions.add_pr_body.pull_request_body.commits + 1.0)"
