apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: github-template
  namespace: tekton-pipelines
spec:
  params:
    - name: gitRevision
    - name: gitRepository
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: TaskRun
      metadata:
        generateName: github-run-
        namespace: test-workloads
      spec:
        inputs:
          resources:
            - name: source
              resourceSpec:
                params:
                  - name: revision
                    value: $(tt.params.gitRevision)
                  - name: url
                    value: $(tt.params.gitRepository)
                type: git
        serviceAccountName: test-runs
        taskSpec:
          inputs:
            resources:
              - name: source
                type: git
          steps:
            - image: ubuntu
              script: |
                #! /bin/bash
                ls -al $(inputs.resources.source.path)
