apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: pull-secret
  namespace: test-workloads
data:
  .dockerconfigjson: {{ .Values.registry.pullSecret.dockerConfigJSON | quote }}
