---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: release-manager
rules:
  - apiGroups:
      - cluster.x-k8s.io
      - infrastructure.giantswarm.io
      - provider.giantswarm.io
      - release.giantswarm.io
      - security.giantswarm.io
      - infrastructure.cluster.x-k8s.io
      - controlplane.cluster.x-k8s.io
      - infrastructure.cluster.x-k8s.io
      - bootstrap.cluster.x-k8s.io
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - "apiextensions.k8s.io"
    resources:
      - "customresourcedefinitions"
    verbs:
      - "get"
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: test-infra-opsctl
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - "applications"
    verbs:
      - "patch"
  - apiGroups:
      - "application.giantswarm.io"
    resources:
      - "apps"
    verbs:
      - "*"
  - apiGroups:
      - "core.giantswarm.io"
    resources:
      - "configs"
    verbs:
      - "*"
