---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: test-infra-release-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: release-manager
subjects:
  - kind: ServiceAccount
    name: test-infra
    namespace: giantswarm
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: test-infra-opsctl
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: test-infra-opsctl
subjects:
  - kind: ServiceAccount
    name: test-infra
    namespace: giantswarm
