kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: release-manager
rules:
  - apiGroups:
      - cluster.x-k8s.io
      - infrastructure.giantswarm.io
      - release.giantswarm.io
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - "*"
    verbs:
      - "*"
