apiVersion: v1
kind: Secret
metadata:
  name: test-infra-token
  namespace: giantswarm
  annotations:
    kubernetes.io/service-account.name: test-infra
type: kubernetes.io/service-account-token
---
kind: ServiceAccount
apiVersion: v1
metadata:
  namespace: giantswarm
  name: test-infra
secrets:
- name: test-infra-token
