apiVersion: v1
kind: Secret
metadata:
  name: sonobuoy-token
  namespace: giantswarm
  annotations:
    kubernetes.io/service-account.name: sonobuoy
type: kubernetes.io/service-account-token
---
kind: ServiceAccount
apiVersion: v1
metadata:
  namespace: giantswarm
  name: sonobuoy
secrets:
- name: sonobuoy-token
