log_level: info

pod_namespace: nightly

prowjob_namespace: prow

# Report job status for presubmit and postsubmit
github_reporter:
  job_types_to_report:
    - presubmit
    - postsubmit

deck:
  external_agent_logs:
    - agent: tekton-pipeline
      url_template: {{`'http://log-aggregator:8000/logs/{{.ObjectMeta.Name}}'`}}

presubmits:
  giantswarm/releases:
  - name: cis
    agent: tekton-pipeline
    max_concurrency: 3
    always_run: false
    skip_report: false
    pipeline_run_spec:
      pipelineRef:
        name: cis
      serviceAccountName: releases
      resources:
      - name: releases
        resourceRef:
          name: PROW_IMPLICIT_GIT_REF
      workspaces:
      - name: cluster
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 10Mi
    trigger: "/test cis"
    rerun_command: "/test cis"
  - name: cncf
    agent: tekton-pipeline
    max_concurrency: 3
    always_run: false
    skip_report: false
    pipeline_run_spec:
      pipelineRef:
        name: cncf
      serviceAccountName: releases
      timeout: 5h0m0s
      resources:
      - name: releases
        resourceRef:
          name: PROW_IMPLICIT_GIT_REF
      workspaces:
      - name: cluster
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 10Mi
    trigger: "/test cncf"
    rerun_command: "/test cncf"
  - name: aws
    agent: tekton-pipeline
    max_concurrency: 3
    always_run: false
    skip_report: false
    pipeline_run_spec:
      pipelineRef:
        name: aws
      serviceAccountName: releases
      resources:
        - name: releases
          resourceRef:
            name: PROW_IMPLICIT_GIT_REF
      workspaces:
        - name: cluster
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 10Mi
    trigger: "/test aws"
    rerun_command: "/test aws"
