log_level: info

pod_namespace: test-workloads

prowjob_namespace: test-infra

# Report job status for presubmit and postsubmit
github_reporter:
  job_types_to_report:
    - presubmit
    - postsubmit

deck:
  external_agent_logs:
    - agent: tekton-pipeline
      url_template: {{`'http://log-aggregator:8000/logs/{{.ObjectMeta.Name}}'`}}

presubmits:
  giantswarm/releases:
  - name: cis
    agent: tekton-pipeline
    max_concurrency: 3
    always_run: false
    skip_report: false
    pipeline_run_spec:
      pipelineRef:
        name: cis
      serviceAccountName: test-runs
      timeout: 5h0m0s
      resources:
      - name: releases
        resourceRef:
          name: PROW_IMPLICIT_GIT_REF
      workspaces:
      - name: cluster
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 10Mi
    trigger: "/test cis"
    rerun_command: "/test cis"
  - name: cncf
    agent: tekton-pipeline
    max_concurrency: 3
    always_run: false
    skip_report: false
    pipeline_run_spec:
      pipelineRef:
        name: cncf
      serviceAccountName: test-runs
      timeout: 10h0m0s
      resources:
      - name: releases
        resourceRef:
          name: PROW_IMPLICIT_GIT_REF
      workspaces:
      - name: cluster
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 10Mi
    trigger: "/test cncf"
    rerun_command: "/test cncf"
  - name: aws
    agent: tekton-pipeline
    max_concurrency: 3
    always_run: false
    skip_report: false
    pipeline_run_spec:
      pipelineRef:
        name: aws
      serviceAccountName: test-runs
      timeout: 5h0m0s
      resources:
        - name: releases
          resourceRef:
            name: PROW_IMPLICIT_GIT_REF
      workspaces:
        - name: cluster
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 10Mi
    trigger: "/test aws$"
    rerun_command: "/test aws"
  - name: aws-china
    agent: tekton-pipeline
    max_concurrency: 3
    always_run: false
    skip_report: false
    pipeline_run_spec:
      pipelineRef:
        name: aws-china
      serviceAccountName: test-runs
      timeout: 5h0m0s
      resources:
        - name: releases
          resourceRef:
            name: PROW_IMPLICIT_GIT_REF
      workspaces:
        - name: cluster
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 10Mi
    trigger: "/test aws-china"
    rerun_command: "/test aws-china"
  - name: azure
    agent: tekton-pipeline
    max_concurrency: 5
    always_run: false
    skip_report: false
    pipeline_run_spec:
      pipelineRef:
        name: azure
      serviceAccountName: test-runs
      timeout: 3h0m0s
      resources:
        - name: releases
          resourceRef:
            name: PROW_IMPLICIT_GIT_REF
      workspaces:
        - name: cluster
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 10Mi
    trigger: "/test azure$"
    rerun_command: "/test azure"
  - name: aws-e2e
    agent: tekton-pipeline
    max_concurrency: 5
    always_run: false
    skip_report: false
    pipeline_run_spec:
      pipelineRef:
        name: aws-e2e
      serviceAccountName: test-runs
      timeout: 3h0m0s
      resources:
        - name: releases
          resourceRef:
            name: PROW_IMPLICIT_GIT_REF
      workspaces:
        - name: cluster
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 10Mi
    trigger: "/test aws-e2e"
    rerun_command: "/test aws-e2e"

  - name: capz
    agent: tekton-pipeline
    max_concurrency: 5
    always_run: false
    skip_report: false
    pipeline_run_spec:
      pipelineRef:
        name: capz
      serviceAccountName: test-runs
      timeout: 3h0m0s
      resources:
        - name: releases
          resourceRef:
            name: PROW_IMPLICIT_GIT_REF
      workspaces:
        - name: cluster
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 10Mi
    trigger: "/test capz"
    rerun_command: "/test capz"

  - name: azure-upgrade
    agent: tekton-pipeline
    max_concurrency: 5
    always_run: false
    skip_report: false
    pipeline_run_spec:
      pipelineRef:
        name: azure-upgrade
      serviceAccountName: test-runs
      timeout: 3h0m0s
      resources:
        - name: releases
          resourceRef:
            name: PROW_IMPLICIT_GIT_REF
      workspaces:
        - name: cluster
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 10Mi
    trigger: "/test azure-upgrade$"
    rerun_command: "/test azure-upgrade"

  - name: upgrade-to-this-azure-operator
    agent: tekton-pipeline
    max_concurrency: 5
    always_run: false
    skip_report: false
    pipeline_run_spec:
      pipelineRef:
        name: upgrade-to-this-azure-operator
      serviceAccountName: test-runs
      timeout: 3h0m0s
      resources:
        - name: releases
          resourceRef:
            name: PROW_IMPLICIT_GIT_REF
      workspaces:
        - name: cluster
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 10Mi
    trigger: "/test upgrade-to-this-azure-operator"
    rerun_command: "/test upgrade-to-this-azure-operator"

  giantswarm/prometheus-meta-operator:
  - name: heartbeat
    agent: tekton-pipeline
    max_concurrency: 1
    always_run: false
    skip_report: false
    pipeline_run_spec:
      pipelineRef:
        name: heartbeat
      serviceAccountName: test-runs
      timeout: 3h0m0s
      workspaces:
        - name: cluster
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 10Mi
    trigger: "/test heartbeat"
    rerun_command: "/test heartbeat"

  giantswarm/cluster-openstack:
  - name: create
    agent: tekton-pipeline
    max_concurrency: 1
    always_run: false
    skip_report: false
    pipeline_run_spec:
      pipelineRef:
        name: create-cluster-capi-pure
      serviceAccountName: test-runs
      timeout: 3h0m0s
      params:
      - name: source-repo-name
        value: cluster-openstack
      - name: provider
        value: openstack
      - name: installation
        value: gamma
      - name: cluster-chart
        value: cluster-openstack
      - name: default-apps-chart
        value: default-apps-openstack
      resources:
      - name: source-repo
        resourceRef:
          name: PROW_IMPLICIT_GIT_REF
      workspaces:
      - name: cluster
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 10Mi
    trigger: "/test create(\\s|$)"
    rerun_command: "/test create"

  giantswarm/default-apps-openstack:
  - name: create
    agent: tekton-pipeline
    max_concurrency: 1
    always_run: false
    skip_report: false
    pipeline_run_spec:
      pipelineRef:
        name: create-cluster-capi-pure
      serviceAccountName: test-runs
      timeout: 3h0m0s
      params:
      - name: source-repo-name
        value: default-apps-openstack
      - name: provider
        value: openstack
      - name: installation
        value: gamma
      - name: cluster-chart
        value: cluster-openstack
      - name: default-apps-chart
        value: default-apps-openstack
      resources:
      - name: source-repo
        resourceRef:
          name: PROW_IMPLICIT_GIT_REF
      workspaces:
      - name: cluster
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 10Mi
    trigger: "/test create(\\s|$)"
    rerun_command: "/test create"

  giantswarm/cluster-aws:
  - name: create
    agent: tekton-pipeline
    max_concurrency: 1
    always_run: false
    skip_report: false
    pipeline_run_spec:
      pipelineRef:
        name: create-cluster-capi-pure
      serviceAccountName: test-runs
      timeout: 3h0m0s
      params:
      - name: source-repo-name
        value: cluster-aws
      - name: provider
        value: aws
      - name: installation
        value: gaia
      - name: cluster-chart
        value: cluster-aws
      - name: default-apps-chart
        value: default-apps-aws
      resources:
      - name: source-repo
        resourceRef:
          name: PROW_IMPLICIT_GIT_REF
      workspaces:
      - name: cluster
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 10Mi
    trigger: "/test create(\\s|$)"
    rerun_command: "/test create"
  - name: upgrade
    agent: tekton-pipeline
    max_concurrency: 1
    always_run: false
    skip_report: false
    pipeline_run_spec:
      pipelineRef:
        name: upgrade-cluster-capi-pure
      serviceAccountName: test-runs
      timeout: 3h0m0s
      params:
        - name: source-repo-name
          value: cluster-aws
        - name: provider
          value: aws
        - name: installation
          value: gaia
        - name: cluster-chart
          value: cluster-aws
        - name: default-apps-chart
          value: default-apps-aws
      resources:
        - name: source-repo
          resourceRef:
            name: PROW_IMPLICIT_GIT_REF
      workspaces:
        - name: cluster
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 10Mi
    trigger: "/test upgrade(\\s|$)"
    rerun_command: "/test upgrade"

  giantswarm/default-apps-aws:
  - name: create
    agent: tekton-pipeline
    max_concurrency: 1
    always_run: false
    skip_report: false
    pipeline_run_spec:
      pipelineRef:
        name: create-cluster-capi-pure
      serviceAccountName: test-runs
      timeout: 3h0m0s
      params:
      - name: source-repo-name
        value: default-apps-aws
      - name: provider
        value: aws
      - name: installation
        value: gaia
      - name: cluster-chart
        value: cluster-aws
      - name: default-apps-chart
        value: default-apps-aws
      resources:
      - name: source-repo
        resourceRef:
          name: PROW_IMPLICIT_GIT_REF
      workspaces:
      - name: cluster
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 10Mi
    trigger: "/test create(\\s|$)"
    rerun_command: "/test create"
  - name: upgrade
    agent: tekton-pipeline
    max_concurrency: 1
    always_run: false
    skip_report: false
    pipeline_run_spec:
      pipelineRef:
        name: upgrade-cluster-capi-pure
      serviceAccountName: test-runs
      timeout: 3h0m0s
      params:
        - name: source-repo-name
          value: default-apps-aws
        - name: provider
          value: aws
        - name: installation
          value: gaia
        - name: cluster-chart
          value: cluster-aws
        - name: default-apps-chart
          value: default-apps-aws
      resources:
        - name: source-repo
          resourceRef:
            name: PROW_IMPLICIT_GIT_REF
      workspaces:
        - name: cluster
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 10Mi
    trigger: "/test upgrade(\\s|$)"
    rerun_command: "/test upgrade"

  giantswarm/cluster-gcp:
  - name: create
    agent: tekton-pipeline
    max_concurrency: 1
    always_run: false
    skip_report: false
    pipeline_run_spec:
      pipelineRef:
        name: create-cluster-capi-pure
      serviceAccountName: test-runs
      timeout: 3h0m0s
      params:
      - name: source-repo-name
        value: cluster-gcp
      - name: provider
        value: gcp
      - name: installation
        value: gunther
      - name: cluster-chart
        value: cluster-gcp
      - name: default-apps-chart
        value: default-apps-gcp
      resources:
      - name: source-repo
        resourceRef:
          name: PROW_IMPLICIT_GIT_REF
      workspaces:
      - name: cluster
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 10Mi
    trigger: "/test create(\\s|$)"
    rerun_command: "/test create"
  - name: upgrade
    agent: tekton-pipeline
    max_concurrency: 1
    always_run: false
    skip_report: false
    pipeline_run_spec:
      pipelineRef:
        name: upgrade-cluster-capi-pure
      serviceAccountName: test-runs
      timeout: 3h0m0s
      params:
        - name: source-repo-name
          value: cluster-gcp
        - name: provider
          value: gcp
        - name: installation
          value: gunther
        - name: cluster-chart
          value: cluster-gcp
        - name: default-apps-chart
          value: default-apps-gcp
      resources:
        - name: source-repo
          resourceRef:
            name: PROW_IMPLICIT_GIT_REF
      workspaces:
        - name: cluster
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 10Mi
    trigger: "/test upgrade(\\s|$)"
    rerun_command: "/test upgrade"

  giantswarm/default-apps-gcp:
  - name: create
    agent: tekton-pipeline
    max_concurrency: 1
    always_run: false
    skip_report: false
    pipeline_run_spec:
      pipelineRef:
        name: create-cluster-capi-pure
      serviceAccountName: test-runs
      timeout: 3h0m0s
      params:
      - name: source-repo-name
        value: default-apps-gcp
      - name: provider
        value: gcp
      - name: installation
        value: gunther
      - name: cluster-chart
        value: cluster-gcp
      - name: default-apps-chart
        value: default-apps-gcp
      resources:
      - name: source-repo
        resourceRef:
          name: PROW_IMPLICIT_GIT_REF
      workspaces:
      - name: cluster
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 10Mi
    trigger: "/test create(\\s|$)"
    rerun_command: "/test create"
  - name: upgrade
    agent: tekton-pipeline
    max_concurrency: 1
    always_run: false
    skip_report: false
    pipeline_run_spec:
      pipelineRef:
        name: upgrade-cluster-capi-pure
      serviceAccountName: test-runs
      timeout: 3h0m0s
      params:
        - name: source-repo-name
          value: default-apps-gcp
        - name: provider
          value: gcp
        - name: installation
          value: gunther
        - name: cluster-chart
          value: cluster-gcp
        - name: default-apps-chart
          value: default-apps-gcp
      resources:
        - name: source-repo
          resourceRef:
            name: PROW_IMPLICIT_GIT_REF
      workspaces:
        - name: cluster
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 10Mi
    trigger: "/test upgrade(\\s|$)"
    rerun_command: "/test upgrade"
