log_level: info

pod_namespace: test-workloads

prowjob_namespace: test-infra

# Report job status for presubmit and postsubmit
github_reporter:
  job_types_to_report:
    - presubmit
    - postsubmit

deck:
  external_agent_logs:
    - agent: tekton-pipeline
      url_template: {{`'http://log-aggregator:8000/logs/{{.ObjectMeta.Name}}'`}}

presubmits:
  giantswarm/releases:
  - name: cis
    agent: tekton-pipeline
    max_concurrency: 3
    always_run: false
    skip_report: false
    pipeline_run_spec:
      pipelineRef:
        name: cis
      serviceAccountName: test-runs
      timeout: 5h0m0s
      resources:
      - name: releases
        resourceRef:
          name: PROW_IMPLICIT_GIT_REF
      workspaces:
      - name: cluster
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 10Mi
    trigger: "/test cis"
    rerun_command: "/test cis"

  - name: cncf
    agent: tekton-pipeline
    max_concurrency: 3
    always_run: false
    skip_report: false
    pipeline_run_spec:
      pipelineRef:
        name: cncf
      serviceAccountName: test-runs
      timeout: 10h0m0s
      resources:
      - name: releases
        resourceRef:
          name: PROW_IMPLICIT_GIT_REF
      workspaces:
      - name: cluster
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 10Mi
    trigger: "/test cncf"
    rerun_command: "/test cncf"

  - name: e2e
    agent: tekton-pipeline
    max_concurrency: 3
    always_run: false
    skip_report: false
    pipeline_run_spec:
      pipelineRef:
        name: e2e
      serviceAccountName: test-runs
      timeout: 5h0m0s
      resources:
        - name: releases
          resourceRef:
            name: PROW_IMPLICIT_GIT_REF
      workspaces:
        - name: cluster
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 10Mi
    trigger: "/test aws|azure|e2e$"
    rerun_command: "/test e2e"

  - name: e2e-china
    agent: tekton-pipeline
    max_concurrency: 3
    always_run: false
    skip_report: false
    pipeline_run_spec:
      pipelineRef:
        name: e2e
      serviceAccountName: test-runs
      timeout: 5h0m0s
      resources:
        - name: releases
          resourceRef:
            name: PROW_IMPLICIT_GIT_REF
      params:
        - name: REGION
          value: china
      workspaces:
        - name: cluster
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 10Mi
    trigger: "/test aws-china|e2e-china"
    rerun_command: "/test e2e-china"

  - name: upgrade
    agent: tekton-pipeline
    max_concurrency: 5
    always_run: false
    skip_report: false
    pipeline_run_spec:
      pipelineRef:
        name: upgrade
      serviceAccountName: test-runs
      timeout: 3h0m0s
      resources:
        - name: releases
          resourceRef:
            name: PROW_IMPLICIT_GIT_REF
      workspaces:
        - name: cluster
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 10Mi
    trigger: "/test upgrade$"
    rerun_command: "/test upgrade"

  - name: upgrade-china
    agent: tekton-pipeline
    max_concurrency: 5
    always_run: false
    skip_report: false
    pipeline_run_spec:
      pipelineRef:
        name: upgrade
      serviceAccountName: test-runs
      timeout: 3h0m0s
      resources:
        - name: releases
          resourceRef:
            name: PROW_IMPLICIT_GIT_REF
      params:
        - name: REGION
          value: china
      workspaces:
        - name: cluster
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 10Mi
    trigger: "/test upgrade-china$"
    rerun_command: "/test upgrade-china"

  giantswarm/cluster-aws:
  - name: create
    agent: tekton-pipeline
    max_concurrency: 1
    always_run: false
    skip_report: false
    pipeline_run_spec:
      pipelineRef:
        name: create-cluster-capi-pure
      serviceAccountName: test-runs
      timeout: 3h0m0s
      params:
      - name: source-repo-name
        value: cluster-aws
      - name: provider
        value: capa
      - name: installation
        value: golem
      - name: cluster-chart
        value: cluster-aws
      - name: default-apps-chart
        value: default-apps-aws
      resources:
      - name: source-repo
        resourceRef:
          name: PROW_IMPLICIT_GIT_REF
      workspaces:
      - name: cluster
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 10Mi
    trigger: "/test create(\\s|$)"
    rerun_command: "/test create"
  - name: upgrade
    agent: tekton-pipeline
    max_concurrency: 1
    always_run: false
    skip_report: false
    pipeline_run_spec:
      pipelineRef:
        name: upgrade-cluster-capi-pure
      serviceAccountName: test-runs
      timeout: 3h0m0s
      params:
        - name: source-repo-name
          value: cluster-aws
        - name: provider
          value: capa
        - name: installation
          value: golem
        - name: cluster-chart
          value: cluster-aws
        - name: default-apps-chart
          value: default-apps-aws
      resources:
        - name: source-repo
          resourceRef:
            name: PROW_IMPLICIT_GIT_REF
      workspaces:
        - name: cluster
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 10Mi
    trigger: "/test upgrade(\\s|$)"
    rerun_command: "/test upgrade"

  giantswarm/default-apps-aws:
  - name: create
    agent: tekton-pipeline
    max_concurrency: 1
    always_run: false
    skip_report: false
    pipeline_run_spec:
      pipelineRef:
        name: create-cluster-capi-pure
      serviceAccountName: test-runs
      timeout: 3h0m0s
      params:
      - name: source-repo-name
        value: default-apps-aws
      - name: provider
        value: capa
      - name: installation
        value: golem
      - name: cluster-chart
        value: cluster-aws
      - name: default-apps-chart
        value: default-apps-aws
      resources:
      - name: source-repo
        resourceRef:
          name: PROW_IMPLICIT_GIT_REF
      workspaces:
      - name: cluster
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 10Mi
    trigger: "/test create(\\s|$)"
    rerun_command: "/test create"
  - name: upgrade
    agent: tekton-pipeline
    max_concurrency: 1
    always_run: false
    skip_report: false
    pipeline_run_spec:
      pipelineRef:
        name: upgrade-cluster-capi-pure
      serviceAccountName: test-runs
      timeout: 3h0m0s
      params:
        - name: source-repo-name
          value: default-apps-aws
        - name: provider
          value: capa
        - name: installation
          value: golem
        - name: cluster-chart
          value: cluster-aws
        - name: default-apps-chart
          value: default-apps-aws
      resources:
        - name: source-repo
          resourceRef:
            name: PROW_IMPLICIT_GIT_REF
      workspaces:
        - name: cluster
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 10Mi
    trigger: "/test upgrade(\\s|$)"
    rerun_command: "/test upgrade"

  giantswarm/cluster-gcp:
  - name: create
    agent: tekton-pipeline
    max_concurrency: 1
    always_run: false
    skip_report: false
    pipeline_run_spec:
      pipelineRef:
        name: create-cluster-capi-pure
      serviceAccountName: test-runs
      timeout: 3h0m0s
      params:
      - name: source-repo-name
        value: cluster-gcp
      - name: provider
        value: gcp
      - name: installation
        value: gunther
      - name: cluster-chart
        value: cluster-gcp
      - name: default-apps-chart
        value: default-apps-gcp
      resources:
      - name: source-repo
        resourceRef:
          name: PROW_IMPLICIT_GIT_REF
      workspaces:
      - name: cluster
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 10Mi
    trigger: "/test create(\\s|$)"
    rerun_command: "/test create"
  - name: upgrade
    agent: tekton-pipeline
    max_concurrency: 1
    always_run: false
    skip_report: false
    pipeline_run_spec:
      pipelineRef:
        name: upgrade-cluster-capi-pure
      serviceAccountName: test-runs
      timeout: 3h0m0s
      params:
        - name: source-repo-name
          value: cluster-gcp
        - name: provider
          value: gcp
        - name: installation
          value: gunther
        - name: cluster-chart
          value: cluster-gcp
        - name: default-apps-chart
          value: default-apps-gcp
      resources:
        - name: source-repo
          resourceRef:
            name: PROW_IMPLICIT_GIT_REF
      workspaces:
        - name: cluster
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 10Mi
    trigger: "/test upgrade(\\s|$)"
    rerun_command: "/test upgrade"

  giantswarm/default-apps-gcp:
  - name: create
    agent: tekton-pipeline
    max_concurrency: 1
    always_run: false
    skip_report: false
    pipeline_run_spec:
      pipelineRef:
        name: create-cluster-capi-pure
      serviceAccountName: test-runs
      timeout: 3h0m0s
      params:
      - name: source-repo-name
        value: default-apps-gcp
      - name: provider
        value: gcp
      - name: installation
        value: gunther
      - name: cluster-chart
        value: cluster-gcp
      - name: default-apps-chart
        value: default-apps-gcp
      resources:
      - name: source-repo
        resourceRef:
          name: PROW_IMPLICIT_GIT_REF
      workspaces:
      - name: cluster
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 10Mi
    trigger: "/test create(\\s|$)"
    rerun_command: "/test create"
  - name: upgrade
    agent: tekton-pipeline
    max_concurrency: 1
    always_run: false
    skip_report: false
    pipeline_run_spec:
      pipelineRef:
        name: upgrade-cluster-capi-pure
      serviceAccountName: test-runs
      timeout: 3h0m0s
      params:
        - name: source-repo-name
          value: default-apps-gcp
        - name: provider
          value: gcp
        - name: installation
          value: gunther
        - name: cluster-chart
          value: cluster-gcp
        - name: default-apps-chart
          value: default-apps-gcp
      resources:
        - name: source-repo
          resourceRef:
            name: PROW_IMPLICIT_GIT_REF
      workspaces:
        - name: cluster
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 10Mi
    trigger: "/test upgrade(\\s|$)"
    rerun_command: "/test upgrade"
