log_level: info

pod_namespace: test-workloads

prowjob_namespace: test-infra

# Report job status for presubmit and postsubmit
github_reporter:
  job_types_to_report:
    - presubmit
    - postsubmit

deck:
  external_agent_logs:
    - agent: tekton-pipeline
      url_template: {{`'http://log-aggregator:8000/logs/{{.ObjectMeta.Name}}'`}}

presubmits:
  giantswarm/giantswarm-todo-app:
  - name: test-app
    agent: tekton-pipeline
    max_concurrency: 1
    always_run: false
    skip_report: false
    pipeline_run_spec:
      pipelineRef:
        name: test-app
      resources:
      - name: app-repository
        resourceRef:
          name: PROW_IMPLICIT_GIT_REF
      - name: releases
        resourceRef:
          name: releases-master
      workspaces:
      - name: cluster
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 10Mi
      # TODO remove this once standup is used for cluster creation
      - name: tenant-kubeconfig
        secret:
          secretName: tenant-kubeconfig
          items:
          - key: kubeconfig
            path: kubeconfig
    trigger: "/test this"
    rerun_command: "/test this"
  giantswarm/releases:
  - name: cis
    agent: tekton-pipeline
    max_concurrency: 3
    always_run: false
    skip_report: false
    pipeline_run_spec:
      pipelineRef:
        name: cis
      serviceAccountName: test-runs
      timeout: 5h0m0s
      resources:
      - name: releases
        resourceRef:
          name: PROW_IMPLICIT_GIT_REF
      workspaces:
      - name: cluster
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 10Mi
    trigger: "/test cis"
    rerun_command: "/test cis"
  - name: cncf
    agent: tekton-pipeline
    max_concurrency: 3
    always_run: false
    skip_report: false
    pipeline_run_spec:
      pipelineRef:
        name: cncf
      serviceAccountName: test-runs
      timeout: 10h0m0s
      resources:
      - name: releases
        resourceRef:
          name: PROW_IMPLICIT_GIT_REF
      workspaces:
      - name: cluster
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 10Mi
    trigger: "/test cncf"
    rerun_command: "/test cncf"
  - name: aws
    agent: tekton-pipeline
    max_concurrency: 3
    always_run: false
    skip_report: false
    pipeline_run_spec:
      pipelineRef:
        name: aws
      serviceAccountName: test-runs
      resources:
        - name: releases
          resourceRef:
            name: PROW_IMPLICIT_GIT_REF
      workspaces:
        - name: cluster
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 10Mi
    trigger: "/test aws"
    rerun_command: "/test aws"
