log_level: info

pod_namespace: test-workloads

prowjob_namespace: test-infra

# Report job status for presubmit and postsubmit
github_reporter:
  job_types_to_report:
    - presubmit
    - postsubmit

deck:
  external_agent_logs:
    - agent: tekton-pipeline
      url_template: {{`'http://log-aggregator:8000/logs/{{.ObjectMeta.Name}}'`}}

presubmits:
  giantswarm/releases:
  - name: apps
    agent: tekton-pipeline
    max_concurrency: 3
    always_run: false
    skip_report: false
    pipeline_run_spec:
      pipelineRef:
        name: apps
      serviceAccountName: test-runs
      timeout: 5h0m0s
      resources:
        - name: releases
          resourceRef:
            name: PROW_IMPLICIT_GIT_REF
      workspaces:
        - name: cluster
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 10Mi
    trigger: "/test apps"
    rerun_command: "/test apps"
  - name: cis
    agent: tekton-pipeline
    max_concurrency: 3
    always_run: false
    skip_report: false
    pipeline_run_spec:
      pipelineRef:
        name: cis
      serviceAccountName: test-runs
      timeout: 5h0m0s
      resources:
      - name: releases
        resourceRef:
          name: PROW_IMPLICIT_GIT_REF
      workspaces:
      - name: cluster
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 10Mi
    trigger: "/test cis"
    rerun_command: "/test cis"
  - name: cncf
    agent: tekton-pipeline
    max_concurrency: 3
    always_run: false
    skip_report: false
    pipeline_run_spec:
      pipelineRef:
        name: cncf
      serviceAccountName: test-runs
      timeout: 10h0m0s
      resources:
      - name: releases
        resourceRef:
          name: PROW_IMPLICIT_GIT_REF
      workspaces:
      - name: sonobuoy
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 10Mi
    trigger: "/test cncf"
    rerun_command: "/test cncf"
  - name: aws
    agent: tekton-pipeline
    max_concurrency: 3
    always_run: false
    skip_report: false
    pipeline_run_spec:
      pipelineRef:
        name: aws
      serviceAccountName: test-runs
      timeout: 5h0m0s
      resources:
        - name: releases
          resourceRef:
            name: PROW_IMPLICIT_GIT_REF
      workspaces:
        - name: cluster
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 10Mi
    trigger: "/test aws$"
    rerun_command: "/test aws"
  - name: aws-china
    agent: tekton-pipeline
    max_concurrency: 3
    always_run: false
    skip_report: false
    pipeline_run_spec:
      pipelineRef:
        name: aws-china
      serviceAccountName: test-runs
      timeout: 5h0m0s
      resources:
        - name: releases
          resourceRef:
            name: PROW_IMPLICIT_GIT_REF
      workspaces:
        - name: cluster
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 10Mi
    trigger: "/test aws-china"
    rerun_command: "/test aws-china"
  - name: aws-full
    agent: tekton-pipeline
    max_concurrency: 3
    always_run: false
    skip_report: false
    pipeline_run_spec:
      pipelineRef:
        name: aws-full
      serviceAccountName: test-runs
      timeout: 5h0m0s
      resources:
        - name: releases
          resourceRef:
            name: PROW_IMPLICIT_GIT_REF
      workspaces:
        - name: cluster
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 10Mi
    trigger: "/test aws-full"
    rerun_command: "/test aws-full"
  - name: azure
    agent: tekton-pipeline
    max_concurrency: 5
    always_run: false
    skip_report: false
    pipeline_run_spec:
      pipelineRef:
        name: azure
      serviceAccountName: test-runs
      timeout: 3h0m0s
      resources:
        - name: releases
          resourceRef:
            name: PROW_IMPLICIT_GIT_REF
      workspaces:
        - name: cluster
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 10Mi
    trigger: "/test azure"
    rerun_command: "/test azure"
  - name: azure-upgrade
    agent: tekton-pipeline
    max_concurrency: 5
    always_run: false
    skip_report: false
    pipeline_run_spec:
      pipelineRef:
        name: azure-upgrade
      serviceAccountName: test-runs
      timeout: 3h0m0s
      resources:
        - name: releases
          resourceRef:
            name: PROW_IMPLICIT_GIT_REF
      workspaces:
        - name: cluster
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 10Mi
    trigger: "/test upgrade-azure"
    rerun_command: "/test upgrade-azure"

  - name: upgrade-to-this-azure-operator
    agent: tekton-pipeline
    max_concurrency: 5
    always_run: false
    skip_report: false
    pipeline_run_spec:
      pipelineRef:
        name: upgrade-to-this-azure-operator
      serviceAccountName: test-runs
      timeout: 3h0m0s
      resources:
        - name: releases
          resourceRef:
            name: PROW_IMPLICIT_GIT_REF
      workspaces:
        - name: cluster
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 10Mi
    trigger: "/test upgrade-to-this-azure-operator"
    rerun_command: "/test upgrade-to-this-azure-operator"
