log_level: info

pod_namespace: test-workloads

prowjob_namespace: test-infra

# Report job status for presubmit and postsubmit
github_reporter:
  job_types_to_report:
    - presubmit
    - postsubmit

deck:
  external_agent_logs:
    - agent: tekton-pipeline
      url_template: {{`'http://log-aggregator:8000/logs/{{.ObjectMeta.Name}}'`}}

presubmits:
  giantswarm/releases:
  - name: cis
    agent: tekton-pipeline
    max_concurrency: 3
    always_run: false
    skip_report: false
    pipeline_run_spec:
      pipelineRef:
        name: cis
      serviceAccountName: test-runs
      timeout: 5h0m0s
      resources:
      - name: releases
        resourceRef:
          name: PROW_IMPLICIT_GIT_REF
      workspaces:
      - name: cluster
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 10Mi
    trigger: "/test cis$"
    rerun_command: "/test cis"

  - name: cncf
    agent: tekton-pipeline
    max_concurrency: 3
    always_run: false
    skip_report: false
    pipeline_run_spec:
      pipelineRef:
        name: cncf
      serviceAccountName: test-runs
      timeout: 10h0m0s
      resources:
      - name: releases
        resourceRef:
          name: PROW_IMPLICIT_GIT_REF
      workspaces:
      - name: cluster
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 10Mi
    trigger: "/test cncf( region=default)?( flavour=default)?( region=default)?$"
    rerun_command: "/test cncf region=default flavour=default"

  - name: cncf-eni
    agent: tekton-pipeline
    max_concurrency: 3
    always_run: false
    skip_report: false
    pipeline_run_spec:
      pipelineRef:
        name: cncf
      serviceAccountName: test-runs
      timeout: 10h0m0s
      resources:
      - name: releases
        resourceRef:
          name: PROW_IMPLICIT_GIT_REF
      params:
      - name: CLUSTER_FLAVOUR
        value: eni
      workspaces:
      - name: cluster
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 10Mi
    trigger: "/test cncf( region=default)?( flavour=eni)?( region=default)?$"
    rerun_command: "/test cncf region=default flavour=eni"

  - name: e2e
    agent: tekton-pipeline
    max_concurrency: 3
    always_run: false
    skip_report: false
    pipeline_run_spec:
      pipelineRef:
        name: e2e
      serviceAccountName: test-runs
      timeout: 5h0m0s
      resources:
        - name: releases
          resourceRef:
            name: PROW_IMPLICIT_GIT_REF
      workspaces:
        - name: cluster
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 10Mi
    trigger: "/test e2e( region=default)?( flavour=default)?( region=default)?$"
    rerun_command: "/test e2e region=default flavour=default"

  - name: e2e-china
    agent: tekton-pipeline
    max_concurrency: 3
    always_run: false
    skip_report: false
    pipeline_run_spec:
      pipelineRef:
        name: e2e
      serviceAccountName: test-runs
      timeout: 5h0m0s
      resources:
        - name: releases
          resourceRef:
            name: PROW_IMPLICIT_GIT_REF
      params:
        - name: REGION
          value: china
      workspaces:
        - name: cluster
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 10Mi
    trigger: "/test e2e( region=china)?( flavour=default)?( region=china)?$"
    rerun_command: "/test e2e region=china flavour=default"

  - name: e2e-eni
    agent: tekton-pipeline
    max_concurrency: 3
    always_run: false
    skip_report: false
    pipeline_run_spec:
      pipelineRef:
        name: e2e
      serviceAccountName: test-runs
      timeout: 5h0m0s
      resources:
        - name: releases
          resourceRef:
            name: PROW_IMPLICIT_GIT_REF
      params:
        - name: CLUSTER_FLAVOUR
          value: eni
      workspaces:
        - name: cluster
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 10Mi
    trigger: "/test e2e( region=default)?( flavour=eni)?( region=default)?$"
    rerun_command: "/test e2e region=default flavour=eni"

  - name: upgrade
    agent: tekton-pipeline
    max_concurrency: 5
    always_run: false
    skip_report: false
    pipeline_run_spec:
      pipelineRef:
        name: upgrade
      serviceAccountName: test-runs
      timeout: 3h0m0s
      resources:
        - name: releases
          resourceRef:
            name: PROW_IMPLICIT_GIT_REF
      workspaces:
        - name: cluster
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 10Mi
    trigger: "/test upgrade( region=default)?( flavour=default)?( region=default)?$"
    rerun_command: "/test upgrade region=default flavour=default"

  - name: upgrade-china
    agent: tekton-pipeline
    max_concurrency: 5
    always_run: false
    skip_report: false
    pipeline_run_spec:
      pipelineRef:
        name: upgrade
      serviceAccountName: test-runs
      timeout: 3h0m0s
      resources:
        - name: releases
          resourceRef:
            name: PROW_IMPLICIT_GIT_REF
      params:
        - name: REGION
          value: china
      workspaces:
        - name: cluster
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 10Mi
    trigger: "/test upgrade( region=china)?( flavour=default)?( region=china)?$"
    rerun_command: "/test upgrade region=china flavour=default"

  - name: upgrade-eni
    agent: tekton-pipeline
    max_concurrency: 5
    always_run: false
    skip_report: false
    pipeline_run_spec:
      pipelineRef:
        name: upgrade
      serviceAccountName: test-runs
      timeout: 3h0m0s
      resources:
        - name: releases
          resourceRef:
            name: PROW_IMPLICIT_GIT_REF
      params:
        - name: CLUSTER_FLAVOUR
          value: eni
      workspaces:
        - name: cluster
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 10Mi
    trigger: "/test upgrade( region=default)?( flavour=eni)?( region=default)?$"
    rerun_command: "/test upgrade region=default flavour=eni"
