apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- name: prowconfig
  namespace: prow
  behavior: merge
  files:
  - configs.yaml
- name: prowplugins
  namespace: prow
  behavior: merge
  files:
  - plugins.yaml
resources:
- cluster/prowconfig.yaml
- cluster/prowplugins.yaml
- cluster/crier.yaml
- cluster/deck.yaml
- cluster/ghproxy.yaml
- cluster/hook.yaml
- cluster/horologium.yaml
- cluster/namespace.yaml
- cluster/needs-rebase.yaml
- cluster/nightly.yaml
- cluster/pipeline.yaml
- cluster/plank.yaml
- cluster/sinker.yaml
- cluster/tide.yaml

