kind: ServiceAccount
apiVersion: v1
metadata:
  namespace: prow
  name: log-aggregator
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: prow
  name: log-aggregator
rules:
  - apiGroups:
      - tekton.dev
      - prow.k8s.io
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - "pods"
      - "pods/log"
    verbs:
      - "get"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: prow
  name: log-aggregator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: log-aggregator
subjects:
  - kind: ServiceAccount
    name: log-aggregator
    namespace: prow
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: prow
  name: log-aggregator
  labels:
    app: log-aggregator
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: log-aggregator
  template:
    metadata:
      labels:
        app: log-aggregator
    spec:
      serviceAccountName: log-aggregator
      containers:
        - name: log-aggregator
          image: tfussell/pipeline:d
          args:
            - -namespace
            - nightly
---
apiVersion: v1
kind: Service
metadata:
  name: log-aggregator
  namespace: prow
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: log-aggregator
  type: ClusterIP
