apiVersion: v1
data:
 {{- range $k, $v := .Values.sonobuoyKubeconfig }}
  {{ $k }}: {{ b64enc $v }}
 {{- end }}
kind: Secret
metadata:
  creationTimestamp: null
  name: sonobuoy-kubeconfig
  namespace: test-workloads
