# You can create this secret by running:
# 1. Make sure your kubeconfig is empty so you don't include unneeded data in the secret
# 2. Run this for every installation you care about:
#      opsctl create kubeconfig -i $installation --certificate-common-name-prefix test-infra --ttl 30 > /dev/null
# 3. kubectl config view --flatten > kubeconfig
# 4. kubectl create secret generic standup-kubeconfig --from-file=kubeconfig=kubeconfig --namespace test-workloads
# 5. rm kubeconfig
apiVersion: v1
data:
  kubeconfig: <KUBECONFIG>
kind: Secret
metadata:
  name: standup-kubeconfig
  namespace: test-workloads
type: Opaque
