apiVersion: v1
data:
  {{- range $k, $v := .Values.standupKubeconfig }}
   {{ $k }}: {{ b64enc $v }}
  {{- end }}
kind: Secret
metadata:
  creationTimestamp: null
  name: standup-kubeconfig
  namespace: test-workloads
