# Format of <CONFIG> is:
# aws:
#   endpoint: <API endpoint URL with protocol prefix>
#   token: <API token (uuid)>
# other-provider:
#   endpoint: <API endpoint URL with protocol prefix>
#   token: <API token (uuid)>
apiVersion: v1
data:
  config: <CONFIG>
kind: Secret
metadata:
  name: standup-endpoints-config
  namespace: test-workloads
type: Opaque
