# Format of <CONFIG> is:
# {
# "aws": {
#    "context": "giantswarm-<CP-name>",
#    "endpoint": <ENDPOINT>,
#    "token": <TOKEN>,
#   },
# "other-provider": {
#    "context": "giantswarm-<CP-name>",
#    "endpoint": <ENDPOINT>,
#    "token": <TOKEN>,
#   },
# }
apiVersion: v1
data:
  config: <CONFIG>
kind: Secret
metadata:
  name: standup-endpoints-config
  namespace: test-workloads
type: Opaque
